[route.getnamespaceproof]
PATH = ["block/:height/namespace/:namespace"]
":height" = "Integer"
":namespace" = "Integer"
DOC = "Get the transactions in a namespace of the given block, along with a proof."