version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    # Group all updates together
    groups:
      all:
        patterns:
        - "*"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/"
    groups:
      # The `all` group should include mainly updates from crates.io which are
      # more likely to succeed without intervention.
      ark:
        patterns:
          - "ark-*"
      cdn:
        patterns:
          - "cdn-*"
      jf:
        patterns:
          - "jf-*"
    schedule:
      interval: "daily"
