[package]
name = "sequencer"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ark-bls12-381 = "0.3.0"
ark-serialize = { version = "0.3.0", features = ["derive"] }
async-trait = "0.1.58"
bincode = "1.3.3"
commit = { git = "https://github.com/EspressoSystems/commit", tag = "0.2.2" }
derive_more = "0.99.17"
hotshot = { git = "ssh://git@github.com/EspressoSystems/hotshot", features = ["async-std-executor", "channel-async-std"] }
hotshot-types = { git = "ssh://git@github.com/EspressoSystems/hotshot", features = ["async-std-executor", "channel-async-std"] }
jf-primitives = { features = ["std"], git = "https://github.com/EspressoSystems/jellyfish.git", tag = "0.1.2" }
serde = { version = "1.0.147", features = ["derive"] }
snafu = "0.7.3"
