[package]
name = "sequencer"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
testing = []

[dev-dependencies]
portpicker = "0.1.1"
surf-disco = { git = "https://github.com/EspressoSystems/surf-disco", tag = "v0.4.0" }
tempfile = "3.4.0"

[dependencies]
ark-bls12-381 = "0.3.0"
ark-serialize = { version = "0.3.0", features = ["derive"] }
async-compatibility-layer = { git = "https://github.com/EspressoSystems/async-compatibility-layer", tag = "1.0.1" }
async-std = "1.12.0"
async-trait = "0.1.61"
bincode = "1.3.3"
clap = { version = "4.1", features = ["derive", "env"] }
cld = "0.5"
commit = { git = "https://github.com/EspressoSystems/commit", tag = "0.2.2" }
derive_more = "0.99.17"
futures = "0.3"
hotshot = { git = "https://github.com/EspressoSystems/hotshot", features = ["async-std-executor", "channel-async-std"], rev = "a154ee55a97ec9522fc043e9b7f6e47557f7956a" }
hotshot-centralized-server = { git = "https://github.com/EspressoSystems/hotshot", features = ["async-std-executor", "channel-async-std"], rev = "a154ee55a97ec9522fc043e9b7f6e47557f7956a" }
hotshot-query-service = { git = "ssh://git@github.com/EspressoSystems/hotshot-query-service.git", tag = "0.0.2" }
hotshot-types = { git = "https://github.com/EspressoSystems/hotshot", features = ["async-std-executor", "channel-async-std"], rev = "a154ee55a97ec9522fc043e9b7f6e47557f7956a" }
jf-primitives = { features = ["std"], git = "https://github.com/EspressoSystems/jellyfish.git", tag = "0.1.2-patch.1" }
nll = { git = "https://github.com/EspressoSystems/nll" }
rand = "0.8.5"
serde = { version = "1.0.152", features = ["derive"] }
snafu = "0.7.4"
tide-disco = { git = "https://github.com/EspressoSystems/tide-disco", tag = "v0.4.0" }
toml = "0.5"
tracing = "0.1"
url = "2.3"
