[package]
name = "sequencer"
version = "0.1.0"
authors = ["Espresso Systems <hello@espressosys.com>"]
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
testing = []

[dev-dependencies]
portpicker = "0.1.1"
rand = "0.8.5"
tempfile = "3.4.0"

[dependencies]
ark-bls12-381 = "0.3.0"
ark-serialize = { version = "0.4.0", features = ["derive"] }
async-compatibility-layer = { git = "https://github.com/EspressoSystems/async-compatibility-layer", tag = "1.2.0" }
async-std = "1.12.0"
async-trait = "0.1.71"
bincode = "1.3.3"
clap = { version = "4.3", features = ["derive", "env"] }
cld = "0.5"
commit = { git = "https://github.com/EspressoSystems/commit", tag = "0.2.2" }
contract-bindings = { path = "../contract-bindings" }
derivative = "2.2"
derive_more = "0.99.17"
either = "1.8.1"
ethers = "2.0"
futures = "0.3"

hotshot = { git = "https://github.com/EspressoSystems/hotshot", features = [
    "async-std-executor",
    "channel-async-std",
] }
hotshot-centralized-server = { git = "https://github.com/EspressoSystems/hotshot", features = [
    "async-std-executor",
    "channel-async-std",
] }
hotshot-testing = { git = "https://github.com/EspressoSystems/hotshot", features = [
    "async-std-executor",
    "channel-async-std",
] }
hotshot-types = { git = "https://github.com/EspressoSystems/hotshot", features = [
    "async-std-executor",
    "channel-async-std",
] }

hotshot-query-service = { git = "https://github.com/EspressoSystems/hotshot-query-service" }

jf-primitives = { git = "https://github.com/EspressoSystems/jellyfish", features = [
    "std",
] }
nll = { git = "https://github.com/EspressoSystems/nll" }
rand = "0.8.5"
sequencer-utils = { path = "../utils" }
serde = { version = "1.0.163", features = ["derive"] }
snafu = "0.7.4"
surf-disco = { git = "https://github.com/EspressoSystems/surf-disco", tag = "v0.4.1" }
tide-disco = { git = "https://github.com/EspressoSystems/tide-disco", tag = "v0.4.1" }
toml = "0.5"
tracing = "0.1"
typenum = { version = "1.15.0", default-features = false, features = [
    "no_std",
] }
url = "2.3"
