[[target]]
files = ["contracts/src/RewardClaim.sol"]
contracts = ["RewardClaim"]

[[target.test_commands]]
kind = "foundry"
args = ["--match-contract", "RewardClaim.*Test", "--no-match-test", "testFuzz_|invariant_|test_Network_"]

[[target]]
files = ["contracts/src/StakeTableV2.sol"]
contracts = ["StakeTableV2"]

[[target.test_commands]]
kind = "foundry"
args = ["--match-contract", "StakeTable.*Test", "--no-match-test", "testFuzz_|invariant_|test_Network_|test_StorageLayout"]
