version: "3"

environment:
  - ESPRESSO_SEQUENCER_DA_SERVER_URL=http://localhost:$ESPRESSO_DA_SERVER_PORT
  - ESPRESSO_SEQUENCER_CONSENSUS_SERVER_URL=http://localhost:$ESPRESSO_CONSENSUS_SERVER_PORT
  - ESPRESSO_SEQUENCER_ORCHESTRATOR_URL=http://localhost:$ESPRESSO_ORCHESTRATOR_PORT
  - ESPRESSO_SEQUENCER_URL=http://localhost:$ESPRESSO_SEQUENCER_API_PORT
  - ESPRESSO_SUBMIT_TRANSACTIONS_SUBMIT_URL=http://localhost:$ESPRESSO_SEQUENCER_API_PORT
  - ESPRESSO_SEQUENCER_L1_PROVIDER=http://localhost:$ESPRESSO_SEQUENCER_L1_PORT
  - ESPRESSO_DEMO_L1_HTTP_PROVIDER=$ESPRESSO_SEQUENCER_L1_PROVIDER
  - ESPRESSO_STATE_RELAY_SERVER_URL=http://localhost:$ESPRESSO_STATE_RELAY_SERVER_PORT

processes:
  # Cheating a bit here but since we don't usually have to debug go-ethereum
  # it's using the docker compose service which is a bit easier.
  demo-l1-network:
    command: docker compose up demo-l1-network --force-recreate --renew-anon-volumes
    readiness_probe:
      exec:
        command: "[ $(docker inspect -f '{{.State.Health.Status}}' espresso-sequencer-demo-l1-network-1) = 'healthy' ]"
      initial_delay_seconds: 5
      period_seconds: 6
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 20

  deploy-contracts:
    # The contract addresses are implicitly inherited from .env. We need to unset these or else the
    # script will think they're already deployed.
    command: unset ESPRESSO_SEQUENCER_HOTSHOT_ADDRESS ESPRESSO_SEQUENCER_LIGHT_CLIENT_PROXY_ADDRESS && deploy
    depends_on:
      demo-l1-network:
        condition: process_healthy
      orchestrator:
        condition: process_healthy

  orchestrator:
    command: orchestrator
    readiness_probe:
      http_get:
        scheme: http
        host: localhost
        port: $ESPRESSO_ORCHESTRATOR_PORT
        path: /healthcheck
      initial_delay_seconds: 0
      period_seconds: 1
      timeout_seconds: 1
      success_threshold: 1
      failure_threshold: 100

  da-server:
    command: web-server
    environment:
      - ESPRESSO_WEB_SERVER_PORT=$ESPRESSO_DA_SERVER_PORT
    depends_on:
      orchestrator:
        condition: process_healthy
    readiness_probe:
      http_get:
        scheme: http
        host: localhost
        port: $ESPRESSO_DA_SERVER_PORT
        path: /healthcheck

  consensus-server:
    command: web-server
    environment:
      - ESPRESSO_WEB_SERVER_PORT=$ESPRESSO_CONSENSUS_SERVER_PORT
    depends_on:
      orchestrator:
        condition: process_healthy
    readiness_probe:
      http_get:
        scheme: http
        host: localhost
        port: $ESPRESSO_CONSENSUS_SERVER_PORT
        path: /healthcheck

  state-relay-server:
    command: state-relay-server
    readiness_probe:
      http_get:
        scheme: http
        host: localhost
        port: $ESPRESSO_STATE_RELAY_SERVER_PORT
        path: /healthcheck

  prover-service:
    command: state-prover -d
    environment:
      - MNEMONIC=$ESPRESSO_SEQUENCER_ETH_MNEMONIC
    depends_on:
      orchestrator:
        condition: process_healthy
      state-relay-server:
        condition: process_healthy
      demo-l1-network:
        condition: process_healthy
      deploy-contracts:
        condition: process_completed

  sequencer0:
    command: sequencer -- http -- query -- catchup -- status -- submit
    environment:
      - ESPRESSO_SEQUENCER_API_PORT=$ESPRESSO_SEQUENCER_API_PORT
      - ESPRESSO_SEQUENCER_API_PEERS=http://localhost:$ESPRESSO_SEQUENCER1_API_PORT
      - ESPRESSO_SEQUENCER_STATE_PEERS=http://localhost:$ESPRESSO_SEQUENCER1_API_PORT
      - ESPRESSO_SEQUENCER_STORAGE_PATH=$ESPRESSO_BASE_STORAGE_PATH/seq0
      - ESPRESSO_SEQUENCER_PRIVATE_STAKING_KEY=$ESPRESSO_DEMO_SEQUENCER_STAKING_PRIVATE_KEY_0
      - ESPRESSO_SEQUENCER_PRIVATE_STATE_KEY=$ESPRESSO_DEMO_SEQUENCER_STATE_PRIVATE_KEY_0
      - ESPRESSO_SEQUENCER_ETH_ACCOUNT_INDEX=10
    depends_on:
      orchestrator:
        condition: process_healthy
      demo-l1-network:
        condition: process_healthy
      state-relay-server:
        condition: process_healthy
    readiness_probe:
      http_get:
        scheme: http
        host: localhost
        port: $ESPRESSO_SEQUENCER_API_PORT
        path: /healthcheck
      failure_threshold: 100

  sequencer1:
    command: sequencer -- http -- query -- catchup -- status
    environment:
      - ESPRESSO_SEQUENCER_API_PORT=$ESPRESSO_SEQUENCER1_API_PORT
      - ESPRESSO_SEQUENCER_API_PEERS=http://localhost:$ESPRESSO_SEQUENCER_API_PORT
      - ESPRESSO_SEQUENCER_STATE_PEERS=http://localhost:$ESPRESSO_SEQUENCER2_API_PORT
      - ESPRESSO_SEQUENCER_STORAGE_PATH=$ESPRESSO_BASE_STORAGE_PATH/seq1
      - ESPRESSO_SEQUENCER_PRIVATE_STAKING_KEY=$ESPRESSO_DEMO_SEQUENCER_STAKING_PRIVATE_KEY_1
      - ESPRESSO_SEQUENCER_PRIVATE_STATE_KEY=$ESPRESSO_DEMO_SEQUENCER_STATE_PRIVATE_KEY_1
      - ESPRESSO_SEQUENCER_ETH_ACCOUNT_INDEX=11
    depends_on:
      orchestrator:
        condition: process_healthy
      demo-l1-network:
        condition: process_healthy
      state-relay-server:
        condition: process_healthy
    readiness_probe:
      http_get:
        scheme: http
        host: localhost
        port: $ESPRESSO_SEQUENCER1_API_PORT
        path: /healthcheck
      failure_threshold: 100

  sequencer2:
    command: sequencer -- http -- catchup -- status
    environment:
      - ESPRESSO_SEQUENCER_API_PORT=$ESPRESSO_SEQUENCER2_API_PORT
      - ESPRESSO_SEQUENCER_STATE_PEERS=http://localhost:$ESPRESSO_SEQUENCER3_API_PORT
      - ESPRESSO_SEQUENCER_STORAGE_PATH=$ESPRESSO_BASE_STORAGE_PATH/seq2
      - ESPRESSO_SEQUENCER_PRIVATE_STAKING_KEY=$ESPRESSO_DEMO_SEQUENCER_STAKING_PRIVATE_KEY_2
      - ESPRESSO_SEQUENCER_PRIVATE_STATE_KEY=$ESPRESSO_DEMO_SEQUENCER_STATE_PRIVATE_KEY_2
      - ESPRESSO_SEQUENCER_ETH_ACCOUNT_INDEX=12
    depends_on:
      orchestrator:
        condition: process_healthy
      demo-l1-network:
        condition: process_healthy
      state-relay-server:
        condition: process_healthy
    readiness_probe:
      http_get:
        scheme: http
        host: localhost
        port: $ESPRESSO_SEQUENCER2_API_PORT
        path: /healthcheck
      failure_threshold: 100

  sequencer3:
    command: sequencer -- http -- catchup -- status
    environment:
      - ESPRESSO_SEQUENCER_API_PORT=$ESPRESSO_SEQUENCER3_API_PORT
      - ESPRESSO_SEQUENCER_STATE_PEERS=http://localhost:$ESPRESSO_SEQUENCER4_API_PORT
      - ESPRESSO_SEQUENCER_STORAGE_PATH=$ESPRESSO_BASE_STORAGE_PATH/seq3
      - ESPRESSO_SEQUENCER_PRIVATE_STAKING_KEY=$ESPRESSO_DEMO_SEQUENCER_STAKING_PRIVATE_KEY_3
      - ESPRESSO_SEQUENCER_PRIVATE_STATE_KEY=$ESPRESSO_DEMO_SEQUENCER_STATE_PRIVATE_KEY_3
      - ESPRESSO_SEQUENCER_ETH_ACCOUNT_INDEX=13
    depends_on:
      orchestrator:
        condition: process_healthy
      demo-l1-network:
        condition: process_healthy
      state-relay-server:
        condition: process_healthy
    readiness_probe:
      http_get:
        scheme: http
        host: localhost
        port: $ESPRESSO_SEQUENCER3_API_PORT
        path: /healthcheck
      failure_threshold: 100

  sequencer4:
    command: sequencer -- http -- catchup -- status
    environment:
      - ESPRESSO_SEQUENCER_API_PORT=$ESPRESSO_SEQUENCER4_API_PORT
      - ESPRESSO_SEQUENCER_STATE_PEERS=http://localhost:$ESPRESSO_SEQUENCER_API_PORT
      - ESPRESSO_SEQUENCER_STORAGE_PATH=$ESPRESSO_BASE_STORAGE_PATH/seq4
      - ESPRESSO_SEQUENCER_PRIVATE_STAKING_KEY=$ESPRESSO_DEMO_SEQUENCER_STAKING_PRIVATE_KEY_4
      - ESPRESSO_SEQUENCER_PRIVATE_STATE_KEY=$ESPRESSO_DEMO_SEQUENCER_STATE_PRIVATE_KEY_4
      - ESPRESSO_SEQUENCER_ETH_ACCOUNT_INDEX=14
    depends_on:
      orchestrator:
        condition: process_healthy
      demo-l1-network:
        condition: process_healthy
      state-relay-server:
        condition: process_healthy
    readiness_probe:
      http_get:
        scheme: http
        host: localhost
        port: $ESPRESSO_SEQUENCER4_API_PORT
        path: /healthcheck
      failure_threshold: 100

  commitment-task:
    command: commitment-task
    depends_on:
      sequencer0:
        condition: process_healthy
      demo-l1-network:
        condition: process_healthy
      deploy-contracts:
        condition: process_completed
    readiness_probe:
      http_get:
        scheme: http
        host: localhost
        port: $ESPRESSO_COMMITMENT_TASK_PORT
        path: /healthcheck
      failure_threshold: 100

  submit-transactions:
    command: submit-transactions
    depends_on:
      sequencer0:
        condition: process_healthy
    readiness_probe:
      http_get:
        scheme: http
        host: localhost
        port: $ESPRESSO_SUBMIT_TRANSACTIONS_PORT
        path: /healthcheck
      failure_threshold: 100

  nasty-client:
    command: nasty-client
    depends_on:
      sequencer0:
        condition: process_healthy
    readiness_probe:
      http_get:
        scheme: http
        host: localhost
        port: $ESPRESSO_NASTY_CLIENT_PORT
        path: /healthcheck
      failure_threshold: 100
