version: "3"

environment:
  - ESPRESSO_SEQUENCER_DA_SERVER_URL=http://localhost:$ESPRESSO_DA_SERVER_PORT
  - ESPRESSO_SEQUENCER_CONSENSUS_SERVER_URL=http://localhost:$ESPRESSO_CONSENSUS_SERVER_PORT
  - ESPRESSO_SEQUENCER_ORCHESTRATOR_URL=http://localhost:$ESPRESSO_ORCHESTRATOR_PORT
  - ESPRESSO_SEQUENCER_URL=http://localhost:$ESPRESSO_SEQUENCER_API_PORT
  - ESPRESSO_SEQUENCER_L1_PROVIDER=http://localhost:$ESPRESSO_SEQUENCER_L1_PORT
  - ESPRESSO_SEQUENCER_L1_WS_PROVIDER=ws://localhost:$ESPRESSO_SEQUENCER_L1_WS_PORT
  - ESPRESSO_DEMO_L1_HTTP_PROVIDER=$ESPRESSO_SEQUENCER_L1_PROVIDER
  - ESPRESSO_DEMO_L1_WS_PROVIDER=$ESPRESSO_SEQUENCER_L1_WS_PROVIDER

processes:
  # Cheating a bit here but since we don't usually have to debug go-ethereum
  # it's using the docker compose service which is a bit easier.
  demo-l1-network:
    command: docker compose up demo-l1-network --force-recreate --renew-anon-volumes

  orchestrator:
    command: orchestrator

  da-server:
    command: web-server
    environment:
      - ESPRESSO_WEB_SERVER_PORT=$ESPRESSO_DA_SERVER_PORT
    depends_on:
      orchestrator:
        condition: service_healthy

  consensus-server:
    command: web-server
    environment:
      - ESPRESSO_WEB_SERVER_PORT=$ESPRESSO_CONSENSUS_SERVER_PORT
    depends_on:
      orchestrator:
        condition: service_healthy

  sequencer0:
    command: sequencer -- http -- query -- submit
    environment:
      - ESPRESSO_SEQUENCER_API_PORT=$ESPRESSO_SEQUENCER_API_PORT
      - ESPRESSO_SEQUENCER_STORAGE_PATH=$ESPRESSO_BASE_STORAGE_PATH/seq0
    depends_on:
      orchestrator:
        condition: service_healthy
      demo-l1-network:
        condition: service_healthy

  sequencer1:
    command: sequencer -- http -- query
    environment:
      - ESPRESSO_SEQUENCER_API_PORT=$ESPRESSO_SEQUENCER1_API_PORT
      - ESPRESSO_SEQUENCER_STORAGE_PATH=$ESPRESSO_BASE_STORAGE_PATH/seq1
    depends_on:
      orchestrator:
        condition: service_healthy
      demo-l1-network:
        condition: service_healthy

  sequencer2:
    command: sequencer -- http -- query
    environment:
      - ESPRESSO_SEQUENCER_API_PORT=$ESPRESSO_SEQUENCER2_API_PORT
      - ESPRESSO_SEQUENCER_STORAGE_PATH=$ESPRESSO_BASE_STORAGE_PATH/seq2
    depends_on:
      orchestrator:
        condition: service_healthy
      demo-l1-network:
        condition: service_healthy

  sequencer3:
    command: sequencer -- http -- query
    environment:
      - ESPRESSO_SEQUENCER_API_PORT=$ESPRESSO_SEQUENCER3_API_PORT
      - ESPRESSO_SEQUENCER_STORAGE_PATH=$ESPRESSO_BASE_STORAGE_PATH/seq3
    depends_on:
      orchestrator:
        condition: service_healthy
      demo-l1-network:
        condition: service_healthy

  sequencer4:
    command: sequencer -- http
    environment:
      - ESPRESSO_SEQUENCER_API_PORT=$ESPRESSO_SEQUENCER4_API_PORT
      - ESPRESSO_SEQUENCER_STORAGE_PATH=$ESPRESSO_BASE_STORAGE_PATH/seq4
    depends_on:
      orchestrator:
        condition: service_healthy
      demo-l1-network:
        condition: service_healthy

  commitment-task:
    command: commitment-task --deploy
    depends_on:
      sequencer0:
        condition: service_healthy
      demo-l1-network:
        condition: service_healthy
