reorder_imports = true
use_try_shorthand = true
match_block_trailing_comma = true
use_field_init_shorthand = true
edition = "2021"
condense_wildcard_suffixes = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"