[package]
authors = ["Espresso Systems <hello@espressosys.com>"]
description = "Types and traits for the HotShot consesus module"
edition = "2021"
name = "hotshot-types"
version = "0.1.11"
license = "MIT"

[[bin]]
name = "mnemonic"
path = "bin/mnemonic.rs"

[features]
gpu-vid = ["jf-advz/gpu-vid"]
test-srs = ["jf-advz/test-srs"]

[dependencies]
alloy = { workspace = true }
anyhow = { workspace = true }
ark-bn254 = { workspace = true }
ark-ed-on-bn254 = { workspace = true }
ark-ff = { workspace = true }
ark-serialize = { workspace = true }
ark-srs = { workspace = true }
ark-std = { workspace = true }
async-broadcast = { workspace = true }
async-lock = { workspace = true }
async-trait = { workspace = true }
bincode = { workspace = true }
bitvec = { workspace = true }
blake3 = { workspace = true }
clap = { workspace = true }
committable = { workspace = true }
derive_more = { workspace = true, features = ["debug"] }
digest = { workspace = true, features = ["rand_core"] }
displaydoc = { version = "0.2.5", default-features = false }
dyn-clone = "1.0.17"
either = { workspace = true }
futures = { workspace = true, features = ["alloc"] }
hotshot-utils = { workspace = true }
jf-crhf = { workspace = true }
jf-pcs = { workspace = true }
jf-rescue = { workspace = true }
jf-signature = { workspace = true, features = ["bls", "schnorr"] }
jf-utils = { workspace = true }
jf-advz = { workspace = true }
lazy_static = { workspace = true }
libp2p-identity = { workspace = true }
memoize = { workspace = true }
mnemonic = "1"
multiaddr = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
serde = { workspace = true }
serde-inline-default = { workspace = true }
serde_bytes = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
tagged-base64 = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
typenum = { workspace = true }
url = { workspace = true }
vbs = { workspace = true }
vec1 = { workspace = true }
vid = { workspace = true }

[lints]
workspace = true
