// This file is @generated by prost-build.
/// Represents a HotShot view number
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ViewNumber {
    #[prost(uint64, tag = "1")]
    pub value: u64,
}
/// Transaction in a namespace
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Transaction {
    #[prost(uint64, tag = "1")]
    pub namespace: u64,
    #[prost(bytes = "vec", tag = "2")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
}
/// Namespace proof query response
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NamespaceProofQueryData {
    #[prost(message, optional, tag = "1")]
    pub proof: ::core::option::Option<NsProof>,
    #[prost(message, repeated, tag = "2")]
    pub transactions: ::prost::alloc::vec::Vec<Transaction>,
}
/// Namespace proof variants (protocol version evolution)
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NsProof {
    #[prost(oneof = "ns_proof::Proof", tags = "1, 2, 3, 4")]
    pub proof: ::core::option::Option<ns_proof::Proof>,
}
/// Nested message and enum types in `NsProof`.
pub mod ns_proof {
    #[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Proof {
        #[prost(message, tag = "1")]
        V0(super::AdvzNsProof),
        #[prost(message, tag = "2")]
        V1(super::AvidMNsProof),
        #[prost(message, tag = "3")]
        V1IncorrectEncoding(super::AvidMIncorrectEncodingNsProof),
        #[prost(message, tag = "4")]
        V2(super::AvidmGf2NsProof),
    }
}
/// V0 proof variant (ADVZ)
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AdvzNsProof {
    #[prost(uint64, tag = "1")]
    pub ns_index: u64,
    #[prost(bytes = "vec", tag = "2")]
    pub ns_payload: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "3")]
    pub ns_proof: ::prost::alloc::string::String,
}
/// V1 proof variant (AvidM)
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AvidMNsProof {
    #[prost(uint64, tag = "1")]
    pub ns_index: u64,
    #[prost(bytes = "vec", tag = "2")]
    pub ns_payload: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "3")]
    pub ns_proof: ::prost::alloc::string::String,
}
/// V1 incorrect encoding variant
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AvidMIncorrectEncodingNsProof {
    #[prost(uint64, tag = "1")]
    pub ns_index: u64,
    #[prost(bytes = "vec", tag = "2")]
    pub ns_payload: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "3")]
    pub ns_proof: ::prost::alloc::string::String,
}
/// V2 proof variant (AvidmGf2)
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AvidmGf2NsProof {
    #[prost(uint64, tag = "1")]
    pub ns_index: u64,
    #[prost(bytes = "vec", tag = "2")]
    pub ns_payload: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "3")]
    pub ns_proof: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetViewNumberRequest {}
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetNamespaceProofRequest {
    #[prost(uint64, tag = "1")]
    pub height: u64,
    #[prost(uint64, tag = "2")]
    pub namespace: u64,
}
