// This file is @generated by prost-build.
/// BLS public key (typically 48 bytes)
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BlsPublicKey {
    #[prost(bytes = "vec", tag = "1")]
    pub key: ::prost::alloc::vec::Vec<u8>,
}
/// Schnorr public key (typically 32 bytes)
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SchnorrPublicKey {
    #[prost(bytes = "vec", tag = "1")]
    pub key: ::prost::alloc::vec::Vec<u8>,
}
/// Network address - either IP or domain name with port
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NetAddr {
    #[prost(oneof = "net_addr::AddrType", tags = "1, 2")]
    pub addr_type: ::core::option::Option<net_addr::AddrType>,
}
/// Nested message and enum types in `NetAddr`.
pub mod net_addr {
    #[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum AddrType {
        #[prost(message, tag = "1")]
        Inet(super::InetAddr),
        #[prost(message, tag = "2")]
        Name(super::NameAddr),
    }
}
/// IP address (v4 or v6) with port
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InetAddr {
    /// IP address string (e.g., "127.0.0.1" or "::1")
    #[prost(string, tag = "1")]
    pub ip: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub port: u32,
}
/// Domain name with port
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NameAddr {
    /// Domain name
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub port: u32,
}
/// Stake table entry for a validator
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StakeTableEntry {
    /// BLS verification key
    #[prost(message, optional, tag = "1")]
    pub stake_key: ::core::option::Option<BlsPublicKey>,
    /// U256 as decimal string
    #[prost(string, tag = "2")]
    pub stake_amount: ::prost::alloc::string::String,
}
/// Peer connection information
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PeerConnectInfo {
    /// X25519 public key (32 bytes)
    #[prost(bytes = "vec", tag = "1")]
    pub x25519_key: ::prost::alloc::vec::Vec<u8>,
    /// P2P network address
    #[prost(message, optional, tag = "2")]
    pub p2p_addr: ::core::option::Option<NetAddr>,
}
/// Complete peer configuration
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PeerConfig {
    /// Stake information
    #[prost(message, optional, tag = "1")]
    pub stake_table_entry: ::core::option::Option<StakeTableEntry>,
    /// State verification key
    #[prost(message, optional, tag = "2")]
    pub state_ver_key: ::core::option::Option<SchnorrPublicKey>,
    /// Optional connection info
    #[prost(message, optional, tag = "3")]
    pub connect_info: ::core::option::Option<PeerConnectInfo>,
}
/// U256 value encoded as hex string
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct U256 {
    /// Hex-encoded value with "0x" prefix (e.g., "0x32fe2fedb43f62b4ee2")
    #[prost(string, tag = "1")]
    pub value: ::prost::alloc::string::String,
}
/// Reward claim input for contract submission
/// Contains all data needed to call the claimRewards function on the L1 contract
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RewardClaimInput {
    /// Ethereum address of the reward recipient
    #[prost(string, tag = "1")]
    pub address: ::prost::alloc::string::String,
    /// Total lifetime rewards for this address (hex-encoded with "0x" prefix for contract)
    #[prost(string, tag = "2")]
    pub lifetime_rewards: ::prost::alloc::string::String,
    /// Auth data containing the Merkle proof and auth root inputs (hex-encoded with "0x" prefix)
    /// This is the encoded RewardAuthData from the contract adapter
    #[prost(string, tag = "3")]
    pub auth_data: ::prost::alloc::string::String,
}
/// Request to get reward claim input (at latest finalized height)
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetRewardClaimInputRequest {
    /// Ethereum address to query rewards for (hex format, e.g. "0x1234...")
    #[prost(string, tag = "1")]
    #[schemars(example = "0x0000000000000000000000000000000000000000")]
    pub address: ::prost::alloc::string::String,
}
/// Reward balance for an address
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RewardBalance {
    /// Balance amount in wei (decimal string)
    #[prost(string, tag = "1")]
    pub amount: ::prost::alloc::string::String,
}
/// Request to get reward balance (at latest finalized height)
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetRewardBalanceRequest {
    /// Ethereum address to query
    #[prost(string, tag = "1")]
    #[schemars(example = "0x0000000000000000000000000000000000000000")]
    pub address: ::prost::alloc::string::String,
}
/// Complete reward account query data with balance and merkle proof
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RewardAccountQueryDataV2 {
    /// Current balance for this account (decimal string)
    #[prost(string, tag = "1")]
    pub balance: ::prost::alloc::string::String,
    /// Merkle proof for this account
    #[prost(message, optional, tag = "2")]
    pub proof: ::core::option::Option<RewardAccountProofV2>,
}
/// Reward account proof containing account address and merkle path
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RewardAccountProofV2 {
    /// Ethereum address of the account
    #[prost(string, tag = "1")]
    pub account: ::prost::alloc::string::String,
    /// Merkle proof (Presence or Absence)
    #[prost(message, optional, tag = "2")]
    pub proof: ::core::option::Option<RewardMerkleProofV2>,
}
/// Merkle proof variant (Presence for existing accounts, Absence for non-existing)
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RewardMerkleProofV2 {
    #[prost(oneof = "reward_merkle_proof_v2::ProofType", tags = "1, 2")]
    #[serde(flatten)]
    pub proof_type: ::core::option::Option<reward_merkle_proof_v2::ProofType>,
}
/// Nested message and enum types in `RewardMerkleProofV2`.
pub mod reward_merkle_proof_v2 {
    #[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum ProofType {
        #[prost(message, tag = "1")]
        Presence(super::MerkleProof),
        #[prost(message, tag = "2")]
        Absence(super::MerkleProof),
    }
}
/// Merkle proof containing leaf position and path to root
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MerkleProof {
    /// Leaf position (account address), TaggedBase64 format
    #[prost(string, tag = "1")]
    pub pos: ::prost::alloc::string::String,
    /// Merkle path from leaf to root (160 levels for binary tree)
    #[prost(message, repeated, tag = "2")]
    pub proof: ::prost::alloc::vec::Vec<MerkleNode>,
}
/// Merkle tree node (one of four variants)
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MerkleNode {
    #[prost(oneof = "merkle_node::NodeType", tags = "1, 2, 3, 4")]
    #[serde(flatten)]
    pub node_type: ::core::option::Option<merkle_node::NodeType>,
}
/// Nested message and enum types in `MerkleNode`.
pub mod merkle_node {
    #[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum NodeType {
        #[prost(message, tag = "1")]
        Empty(super::Empty),
        #[prost(message, tag = "2")]
        Leaf(super::Leaf),
        #[prost(message, tag = "3")]
        Branch(super::Branch),
        #[prost(message, tag = "4")]
        ForgottenSubtree(super::ForgottenSubtree),
    }
}
/// Dummy message for flattening Empty
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EmptyData {}
/// Empty node variant (no data)
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Empty {
    /// Dummy field for serde flatten compatibility (must be a message type)
    #[prost(message, optional, tag = "1")]
    #[serde(skip)]
    pub dummy: ::core::option::Option<EmptyData>,
}
/// Leaf node containing account and reward amount
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Leaf {
    /// Leaf position (account address), TaggedBase64 format
    #[prost(string, tag = "1")]
    pub pos: ::prost::alloc::string::String,
    /// Reward amount (U256), TaggedBase64 format
    #[prost(string, tag = "2")]
    pub elem: ::prost::alloc::string::String,
    /// Node hash value, TaggedBase64 format
    #[prost(string, tag = "3")]
    pub value: ::prost::alloc::string::String,
}
/// Branch node with hash and children
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Branch {
    /// Hash value, TaggedBase64 format
    #[prost(string, tag = "1")]
    pub value: ::prost::alloc::string::String,
    /// Child nodes (up to 2 for binary tree)
    #[prost(message, repeated, tag = "2")]
    pub children: ::prost::alloc::vec::Vec<MerkleNode>,
}
/// Forgotten subtree node with hash only
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ForgottenSubtree {
    /// Hash value, TaggedBase64 format
    #[prost(string, tag = "1")]
    pub value: ::prost::alloc::string::String,
}
/// Request to get reward account proof (at latest finalized height)
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetRewardAccountProofRequest {
    /// Ethereum address to query
    #[prost(string, tag = "1")]
    #[schemars(example = "0x0000000000000000000000000000000000000000")]
    pub address: ::prost::alloc::string::String,
}
/// Single reward amount entry
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RewardAmount {
    /// Ethereum address
    #[prost(string, tag = "1")]
    pub address: ::prost::alloc::string::String,
    /// Reward amount in wei (decimal string)
    #[prost(string, tag = "2")]
    pub amount: ::prost::alloc::string::String,
}
/// Paginated list of reward balances
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RewardBalances {
    /// List of reward amounts in this page
    #[prost(message, repeated, tag = "1")]
    pub amounts: ::prost::alloc::vec::Vec<RewardAmount>,
    /// Total number of accounts with rewards at this height
    #[prost(uint64, tag = "2")]
    pub total: u64,
}
/// Request to get paginated reward balances
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetRewardBalancesRequest {
    /// Block height to query
    #[prost(uint64, tag = "1")]
    #[schemars(example = "1000000")]
    pub height: u64,
    /// Starting offset for pagination
    #[prost(uint64, tag = "2")]
    #[schemars(example = "0")]
    pub offset: u64,
    /// Maximum number of results (limit ≤ 10000)
    #[prost(uint64, tag = "3")]
    #[schemars(example = "100")]
    pub limit: u64,
}
/// Raw RewardMerkleTreeV2 snapshot data
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RewardMerkleTreeV2Data {
    /// Serialized merkle tree data
    #[prost(bytes = "vec", tag = "1")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
/// Request to get reward merkle tree snapshot
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetRewardMerkleTreeRequest {
    /// Block height to query
    #[prost(uint64, tag = "1")]
    #[schemars(example = "1000000")]
    pub height: u64,
}
/// ADVZ (VID V0) namespace proof
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AdvzNsProof {
    #[prost(uint32, tag = "1")]
    pub namespace_id: u32,
    #[prost(bytes = "vec", tag = "2")]
    pub ns_payload: ::prost::alloc::vec::Vec<u8>,
    /// VID proof (serialized)
    #[prost(bytes = "vec", optional, tag = "3")]
    pub ns_proof: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
/// AvidM (VID V1) namespace proof
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AvidMNsProof {
    #[prost(uint64, tag = "1")]
    pub ns_index: u64,
    #[prost(bytes = "vec", tag = "2")]
    pub ns_payload: ::prost::alloc::vec::Vec<u8>,
    /// Merkle proof (serialized)
    #[prost(bytes = "vec", tag = "3")]
    pub ns_proof: ::prost::alloc::vec::Vec<u8>,
}
/// AvidM incorrect encoding proof
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AvidMIncorrectEncodingNsProof {
    /// Serialized incorrect encoding proof
    #[prost(bytes = "vec", tag = "1")]
    pub proof_data: ::prost::alloc::vec::Vec<u8>,
}
/// AvidmGf2 (VID V2) namespace proof
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AvidmGf2NsProof {
    #[prost(uint64, tag = "1")]
    pub ns_index: u64,
    #[prost(bytes = "vec", tag = "2")]
    pub ns_payload: ::prost::alloc::vec::Vec<u8>,
    /// Merkle proof (serialized)
    #[prost(bytes = "vec", tag = "3")]
    pub ns_proof: ::prost::alloc::vec::Vec<u8>,
}
/// Namespace proof - supports multiple VID versions
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NsProof {
    #[prost(oneof = "ns_proof::ProofVersion", tags = "1, 2, 3, 4")]
    pub proof_version: ::core::option::Option<ns_proof::ProofVersion>,
}
/// Nested message and enum types in `NsProof`.
pub mod ns_proof {
    #[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum ProofVersion {
        #[prost(message, tag = "1")]
        V0(super::AdvzNsProof),
        #[prost(message, tag = "2")]
        V1(super::AvidMNsProof),
        #[prost(message, tag = "3")]
        V1IncorrectEncoding(super::AvidMIncorrectEncodingNsProof),
        #[prost(message, tag = "4")]
        V2(super::AvidmGf2NsProof),
    }
}
/// Request to get namespace proof for a single block
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetNamespaceProofRequest {
    /// Namespace ID
    #[prost(uint32, tag = "1")]
    pub namespace_id: u32,
    /// Block height
    #[prost(uint64, tag = "2")]
    pub block_height: u64,
}
/// Request to get namespace proofs for a range of blocks
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetNamespaceProofRangeRequest {
    /// Namespace ID
    #[prost(uint32, tag = "1")]
    pub namespace_id: u32,
    /// Starting block height (inclusive)
    #[prost(uint64, tag = "2")]
    pub from: u64,
    /// Ending block height (exclusive)
    #[prost(uint64, tag = "3")]
    pub until: u64,
}
/// Namespace proof response containing transactions and proof
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NamespaceProofResponse {
    /// Transactions for this namespace (each transaction is serialized bytes)
    #[prost(bytes = "vec", repeated, tag = "1")]
    pub transactions: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    /// Namespace proof (optional - may be None if namespace not present)
    #[prost(message, optional, tag = "2")]
    pub proof: ::core::option::Option<NsProof>,
}
/// Response for range queries - array of namespace proofs
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NamespaceProofRangeResponse {
    /// Proofs for each block in the range
    #[prost(message, repeated, tag = "1")]
    pub proofs: ::prost::alloc::vec::Vec<NamespaceProofResponse>,
}
/// Request to get incorrect encoding proof
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetIncorrectEncodingProofRequest {
    /// Namespace ID
    #[prost(uint32, tag = "1")]
    pub namespace_id: u32,
    /// Block height
    #[prost(uint64, tag = "2")]
    pub block_height: u64,
}
/// Incorrect encoding proof response
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct IncorrectEncodingProofResponse {
    /// Incorrect encoding proof (AvidM V1.1 proof)
    #[prost(message, optional, tag = "1")]
    pub proof: ::core::option::Option<AvidMIncorrectEncodingNsProof>,
}
/// Light client state
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LightClientState {
    #[prost(uint64, tag = "1")]
    pub view_number: u64,
    #[prost(uint64, tag = "2")]
    pub block_height: u64,
    /// CircuitField serialized as bytes
    #[prost(bytes = "vec", tag = "3")]
    pub block_comm_root: ::prost::alloc::vec::Vec<u8>,
}
/// Stake table state commitments
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StakeTableState {
    /// CircuitField as bytes
    #[prost(bytes = "vec", tag = "1")]
    pub bls_key_comm: ::prost::alloc::vec::Vec<u8>,
    /// CircuitField as bytes
    #[prost(bytes = "vec", tag = "2")]
    pub schnorr_key_comm: ::prost::alloc::vec::Vec<u8>,
    /// CircuitField as bytes
    #[prost(bytes = "vec", tag = "3")]
    pub amount_comm: ::prost::alloc::vec::Vec<u8>,
    /// CircuitField as bytes
    #[prost(bytes = "vec", tag = "4")]
    pub threshold: ::prost::alloc::vec::Vec<u8>,
}
/// State signature tuple (key + two signatures)
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StateSignatureTuple {
    /// Schnorr public key
    #[prost(message, optional, tag = "1")]
    pub state_signature_key: ::core::option::Option<SchnorrPublicKey>,
    /// LCV3 Schnorr signature
    #[prost(bytes = "vec", tag = "2")]
    pub lcv3_signature: ::prost::alloc::vec::Vec<u8>,
    /// LCV2 Schnorr signature
    #[prost(bytes = "vec", tag = "3")]
    pub lcv2_signature: ::prost::alloc::vec::Vec<u8>,
}
/// Light client state update certificate V2
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LightClientStateUpdateCertificateV2 {
    #[prost(uint64, tag = "1")]
    pub epoch: u64,
    #[prost(message, optional, tag = "2")]
    pub light_client_state: ::core::option::Option<LightClientState>,
    #[prost(message, optional, tag = "3")]
    pub next_stake_table_state: ::core::option::Option<StakeTableState>,
    #[prost(message, repeated, tag = "4")]
    pub signatures: ::prost::alloc::vec::Vec<StateSignatureTuple>,
    /// 32 bytes
    #[prost(bytes = "vec", tag = "5")]
    pub auth_root: ::prost::alloc::vec::Vec<u8>,
}
/// Request to get state certificate for an epoch
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetStateCertificateRequest {
    /// Epoch number
    #[prost(uint64, tag = "1")]
    pub epoch: u64,
}
/// State certificate response
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StateCertificateResponse {
    /// Structured light client state update certificate
    #[prost(message, optional, tag = "1")]
    pub certificate: ::core::option::Option<LightClientStateUpdateCertificateV2>,
}
/// Request to get stake table for an epoch
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetStakeTableRequest {
    /// Epoch number
    #[prost(uint64, tag = "1")]
    pub epoch: u64,
}
/// Stake table response
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StakeTableResponse {
    /// List of peer configurations
    #[prost(message, repeated, tag = "1")]
    pub peers: ::prost::alloc::vec::Vec<PeerConfig>,
}
