// This file is @generated by prost-build.
/// U256 value encoded as hex string
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct U256 {
    /// Hex-encoded value with "0x" prefix (e.g., "0x32fe2fedb43f62b4ee2")
    #[prost(string, tag = "1")]
    pub value: ::prost::alloc::string::String,
}
/// Reward claim input for contract submission
/// Contains all data needed to call the claimRewards function on the L1 contract
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RewardClaimInput {
    /// Ethereum address of the reward recipient
    #[prost(string, tag = "1")]
    pub address: ::prost::alloc::string::String,
    /// Total lifetime rewards for this address (hex-encoded with "0x" prefix for contract)
    #[prost(string, tag = "2")]
    pub lifetime_rewards: ::prost::alloc::string::String,
    /// Auth data containing the Merkle proof and auth root inputs (hex-encoded with "0x" prefix)
    /// This is the encoded RewardAuthData from the contract adapter
    #[prost(string, tag = "3")]
    pub auth_data: ::prost::alloc::string::String,
}
/// Request to get reward claim input (at latest finalized height)
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetRewardClaimInputRequest {
    /// Ethereum address to query rewards for (hex format, e.g. "0x1234...")
    #[prost(string, tag = "1")]
    #[schemars(example = "0x0000000000000000000000000000000000000000")]
    pub address: ::prost::alloc::string::String,
}
/// Reward balance for an address
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RewardBalance {
    /// Balance amount in wei (decimal string)
    #[prost(string, tag = "1")]
    pub amount: ::prost::alloc::string::String,
}
/// Request to get reward balance (at latest finalized height)
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetRewardBalanceRequest {
    /// Ethereum address to query
    #[prost(string, tag = "1")]
    #[schemars(example = "0x0000000000000000000000000000000000000000")]
    pub address: ::prost::alloc::string::String,
}
/// Complete reward account query data with balance and merkle proof
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RewardAccountQueryDataV2 {
    /// Current balance for this account (decimal string)
    #[prost(string, tag = "1")]
    pub balance: ::prost::alloc::string::String,
    /// Merkle proof for this account
    #[prost(message, optional, tag = "2")]
    pub proof: ::core::option::Option<RewardAccountProofV2>,
}
/// Reward account proof containing account address and merkle path
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RewardAccountProofV2 {
    /// Ethereum address of the account
    #[prost(string, tag = "1")]
    pub account: ::prost::alloc::string::String,
    /// Merkle proof (Presence or Absence)
    #[prost(message, optional, tag = "2")]
    pub proof: ::core::option::Option<RewardMerkleProofV2>,
}
/// Merkle proof variant (Presence for existing accounts, Absence for non-existing)
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RewardMerkleProofV2 {
    #[prost(oneof = "reward_merkle_proof_v2::ProofType", tags = "1, 2")]
    #[serde(flatten)]
    pub proof_type: ::core::option::Option<reward_merkle_proof_v2::ProofType>,
}
/// Nested message and enum types in `RewardMerkleProofV2`.
pub mod reward_merkle_proof_v2 {
    #[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum ProofType {
        #[prost(message, tag = "1")]
        Presence(super::MerkleProof),
        #[prost(message, tag = "2")]
        Absence(super::MerkleProof),
    }
}
/// Merkle proof containing leaf position and path to root
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MerkleProof {
    /// Leaf position (account address), TaggedBase64 format
    #[prost(string, tag = "1")]
    pub pos: ::prost::alloc::string::String,
    /// Merkle path from leaf to root (160 levels for binary tree)
    #[prost(message, repeated, tag = "2")]
    pub proof: ::prost::alloc::vec::Vec<MerkleNode>,
}
/// Merkle tree node (one of four variants)
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MerkleNode {
    #[prost(oneof = "merkle_node::NodeType", tags = "1, 2, 3, 4")]
    #[serde(flatten)]
    pub node_type: ::core::option::Option<merkle_node::NodeType>,
}
/// Nested message and enum types in `MerkleNode`.
pub mod merkle_node {
    #[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum NodeType {
        #[prost(message, tag = "1")]
        Empty(super::Empty),
        #[prost(message, tag = "2")]
        Leaf(super::Leaf),
        #[prost(message, tag = "3")]
        Branch(super::Branch),
        #[prost(message, tag = "4")]
        ForgottenSubtree(super::ForgottenSubtree),
    }
}
/// Dummy message for flattening Empty
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EmptyData {}
/// Empty node variant (no data)
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Empty {
    /// Dummy field for serde flatten compatibility (must be a message type)
    #[prost(message, optional, tag = "1")]
    #[serde(skip)]
    pub dummy: ::core::option::Option<EmptyData>,
}
/// Leaf node containing account and reward amount
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Leaf {
    /// Leaf position (account address), TaggedBase64 format
    #[prost(string, tag = "1")]
    pub pos: ::prost::alloc::string::String,
    /// Reward amount (U256), TaggedBase64 format
    #[prost(string, tag = "2")]
    pub elem: ::prost::alloc::string::String,
    /// Node hash value, TaggedBase64 format
    #[prost(string, tag = "3")]
    pub value: ::prost::alloc::string::String,
}
/// Branch node with hash and children
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Branch {
    /// Hash value, TaggedBase64 format
    #[prost(string, tag = "1")]
    pub value: ::prost::alloc::string::String,
    /// Child nodes (up to 2 for binary tree)
    #[prost(message, repeated, tag = "2")]
    pub children: ::prost::alloc::vec::Vec<MerkleNode>,
}
/// Forgotten subtree node with hash only
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ForgottenSubtree {
    /// Hash value, TaggedBase64 format
    #[prost(string, tag = "1")]
    pub value: ::prost::alloc::string::String,
}
/// Request to get reward account proof (at latest finalized height)
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetRewardAccountProofRequest {
    /// Ethereum address to query
    #[prost(string, tag = "1")]
    #[schemars(example = "0x0000000000000000000000000000000000000000")]
    pub address: ::prost::alloc::string::String,
}
/// Single reward amount entry
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RewardAmount {
    /// Ethereum address
    #[prost(string, tag = "1")]
    pub address: ::prost::alloc::string::String,
    /// Reward amount in wei (decimal string)
    #[prost(string, tag = "2")]
    pub amount: ::prost::alloc::string::String,
}
/// Paginated list of reward balances
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RewardBalances {
    /// List of reward amounts in this page
    #[prost(message, repeated, tag = "1")]
    pub amounts: ::prost::alloc::vec::Vec<RewardAmount>,
    /// Total number of accounts with rewards at this height
    #[prost(uint64, tag = "2")]
    pub total: u64,
}
/// Request to get paginated reward balances
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetRewardBalancesRequest {
    /// Block height to query
    #[prost(uint64, tag = "1")]
    #[schemars(example = "1000000")]
    pub height: u64,
    /// Starting offset for pagination
    #[prost(uint64, tag = "2")]
    #[schemars(example = "0")]
    pub offset: u64,
    /// Maximum number of results (limit ≤ 10000)
    #[prost(uint64, tag = "3")]
    #[schemars(example = "100")]
    pub limit: u64,
}
/// Raw RewardMerkleTreeV2 snapshot data
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RewardMerkleTreeV2Data {
    /// Serialized merkle tree data
    #[prost(bytes = "vec", tag = "1")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
/// Request to get reward merkle tree snapshot
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetRewardMerkleTreeRequest {
    /// Block height to query
    #[prost(uint64, tag = "1")]
    #[schemars(example = "1000000")]
    pub height: u64,
}
