//! The v2 API contract: everything in this crate is generated by `build.rs` from the
//! proto files in `proto/`. The proto file is the single definition site for an
//! endpoint: the rpc signature gives the types, the `google.api.http` option gives the
//! HTTP route, and rpc comments give the docs.

/// Message types plus tonic client and server stubs.
pub mod v2 {
    include!("generated/espresso.api.v2.rs");
}

/// Axum REST handlers derived from the `google.api.http` annotations, transcoding
/// HTTP/JSON onto the tonic service traits.
pub mod rest {
    // The generator emits `#[expect]` attributes that not every handler fulfills.
    #![allow(unfulfilled_lint_expectations)]

    include!("generated/espresso.api.v2.rest.rs");
}

pub use v2::*;

/// The compiled proto descriptor set, for gRPC reflection.
pub const FILE_DESCRIPTOR_SET: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/descriptor.bin"));
