[package]
name = "espresso-types"
version = "0.1.0"
authors = ["Espresso Systems <hello@espressosys.com>"]
edition = "2021"

[package.metadata.cargo-machete]
ignored = ["base64_bytes", "hotshot_testing"]

# TODO: fix comments so doctests don't fail
[lib]
doctest = false

[features]
testing = ["hotshot-query-service/testing"]

[dependencies]
alloy = { workspace = true }
alloy-compat = { path = "../alloy-compat" }
anyhow = { workspace = true }
ark-ec = { workspace = true }
ark-serialize = { workspace = true }
ark-std = { workspace = true }
async-broadcast = { workspace = true }
async-lock = { workspace = true }
async-trait = { workspace = true }
base64-bytes = { workspace = true }
bigdecimal = "0.4.8"
bincode = { workspace = true }
blake3 = { workspace = true }
bytesize = { workspace = true }
clap = { workspace = true }
cld = { workspace = true }
committable = { workspace = true }
derive_more = { workspace = true }
either = { workspace = true }
ethers-core = "2.0"
fluent-asserter = "0.1.9"
futures = { workspace = true }
hotshot = { workspace = true }
hotshot-contract-adapter = { workspace = true }
hotshot-example-types = { workspace = true }
hotshot-libp2p-networking = { workspace = true }
hotshot-query-service = { workspace = true }
hotshot-types = { workspace = true }
humantime = "2"
indexmap = { workspace = true }
itertools = { workspace = true }
jf-advz = { workspace = true }
jf-merkle-tree-compat = { workspace = true }
jf-utils = { workspace = true }                                      # TODO temporary: used only for test_rng()
lru = { workspace = true }
num-traits = { workspace = true }
parking_lot = "0.12"
paste = { workspace = true }
pretty_assertions = { workspace = true }
rand = { workspace = true }
sequencer-utils = { path = "../utils" }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }                                                         # TODO temporary, used only for VID, should be set in hotshot
sha3 = "0.10"
static_assertions = { workspace = true }
surf-disco = { workspace = true }
tagged-base64 = { workspace = true }
thiserror = { workspace = true }
tide-disco = { workspace = true }
time = { workspace = true }
tokio = { workspace = true }
tower-service = { version = "0.3", default-features = false }
tracing = { workspace = true }
url = { workspace = true }
vbs = { workspace = true }
vec1 = { workspace = true }
vid = { workspace = true }

[dev-dependencies]
espresso-contract-deployer = { path = "../contracts/rust/deployer" }
espresso-types = { path = ".", features = [ "testing" ] }
portpicker = { workspace = true }
rstest = { workspace = true }
rstest_reuse = { workspace = true }
test-log = { workspace = true }

[lints]
workspace = true
