[package]
name = "espresso-types"
version = "0.1.0"
authors = ["Espresso Systems <hello@espressosys.com>"]
edition = "2021"

[dependencies]
contract-bindings = { path = "../contract-bindings" }
sequencer-utils = { path = "../utils" }

anyhow = { workspace = true }
ark-serialize = { workspace = true }
base64-bytes = { workspace = true }
committable = { workspace = true }
derivative = { workspace = true }
derive_more = { workspace = true }
ethers = { workspace = true }
itertools = { workspace = true }
jf-merkle-tree = { workspace = true }
hotshot-types = { workspace = true }
num-traits = { workspace = true }
serde = { workspace = true }
static_assertions = { workspace = true }
vbs = { workspace = true }
