[package]
name = "espresso-types"
version = "0.1.0"
authors = ["Espresso Systems <hello@espressosys.com>"]
edition = "2021"

[dependencies]
contract-bindings = { path = "../contract-bindings" }
sequencer-utils = { path = "../utils" }

anyhow = { workspace = true }
async-compatibility-layer = { workspace = true }
async-once-cell = { workspace = true }
async-std = { workspace = true } 
async-trait = { workspace = true }
ark-serialize = { workspace = true }
base64-bytes = { workspace = true }
bincode = "1.3.3"
blake3 = { workspace = true }
committable = { workspace = true }
derivative = { workspace = true }
derive_more = { workspace = true }
ethers = { workspace = true }
itertools = { workspace = true }
jf-merkle-tree = { workspace = true }
tracing = { workspace = true }
hotshot-types = { workspace = true }
num-traits = { workspace = true }
serde = { workspace = true }
snafu = { workspace = true }
static_assertions = { workspace = true }
vbs = { workspace = true }
jf-vid = { workspace = true }
url = { workspace = true }
trait-set = "0.3.0"
futures = { workspace = true } 
time = "0.3"
hotshot = { workspace = true } 
sha2 = "0.10" # TODO temporary, used only for VID, should be set in hotshot
hotshot-query-service = { workspace = true, features = ["testing"] }