[package]
name = "ethers-conv"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
alloy = { workspace = true }
ethers = { workspace = true }
workspace-hack = { version = "0.1", path = "../workspace-hack" }
