[package]
name = "hotshot-builder-api"
version = "0.1.7"
edition.workspace = true
license = "MIT"

[dependencies]
async-trait = { workspace = true }
axum = { workspace = true }
committable = { workspace = true }
disco-types = { workspace = true }
hotshot-types = { workspace = true }
http-client = { workspace = true }
http-wire = { workspace = true, features = ["server"] }
serde = { workspace = true }
tagged-base64 = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }
vbs = { workspace = true }

[lints]
workspace = true
