[package]
authors = { workspace = true }
description = "Async task implementations for consensus"
edition = { workspace = true }
name = "hotshot-task-impls"
version = { workspace = true }
license = "MIT"

[dependencies]
async-broadcast = { workspace = true }
async-lock = { workspace = true }
async-trait = { workspace = true }
bincode = { workspace = true }
chrono = { workspace = true }
committable = { workspace = true }
either = { workspace = true }
futures = { workspace = true }
hotshot-builder-api = { workspace = true }
hotshot-contract-adapter = { workspace = true }
hotshot-libp2p-networking = { workspace = true }
hotshot-task = { workspace = true }
hotshot-types = { workspace = true }
hotshot-utils = { workspace = true }
http-client = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }
tagged-base64 = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
vbs = { workspace = true }
vec1 = { workspace = true }
versions = { workspace = true }

[lints]
workspace = true
