{
 "title": "Espresso Sequencer",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "prometheusDS", "label": "Prometheus Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Consensus Last Decided View",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(consensus_last_decided_view[1m])",
     "legendFormat": "{{release}}"
    }
   ]
  },
  {
   "title": "Current View vs Last Decided View",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "rate(consensus_current_view[1m])",
     "legendFormat": "{{release}}-current"
    },
    {
     "expr": "rate(consensus_last_decided_view[1m])",
     "legendFormat": "{{release}}-last"
    }
   ]
  },
  {
   "title": "Consensus Current View",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(consensus_current_view[1m])",
     "legendFormat": "{{release}}"
    }
   ]
  },
  {
   "title": "Outstanding Transactions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "consensus_outstanding_transactions",
     "legendFormat": "{{release}}"
    }
   ]
  },
  {
   "title": "Last Decided Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 8 },
   "targets": [
    { "expr": "consensus_last_decided_time", "legendFormat": "{{release}}" }
   ]
  },
  {
   "title": "Libp2p Connected Peers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "consensus_libp2p_num_connected_peers",
     "legendFormat": "{{release}}"
    }
   ]
  },
  {
   "title": "View Duration as Leader",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 15 },
   "targets": [
    {
     "expr": "consensus_view_duration_as_leader_bucket",
     "legendFormat": "{{release}}"
    }
   ]
  },
  {
   "title": "Timeouts as Leader",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 22 },
   "targets": [
    {
     "expr": "consensus_number_of_timeouts_as_leader",
     "legendFormat": "{{release}}"
    }
   ]
  }
 ]
}