name: Install process-compose
description: Install process-compose from GitHub releases

inputs:
  version:
    description: Version to install (e.g., v1.75.2 or latest)
    required: false
    default: latest

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        set -euxo pipefail

        TAG="${{ inputs.version }}"

        ./scripts/download-github-release.sh \
          --repo F1bonacc1/process-compose \
          --asset process-compose_linux_amd64.tar.gz \
          --tag "$TAG" \
          --extract-to /tmp \
          --extract-file process-compose

        sudo mv /tmp/process-compose /usr/local/bin/
        sudo chmod +x /usr/local/bin/process-compose
        process-compose version
