[package]
name = "hotshot-state-prover"
description = "Generate state update proof for HotShot light client"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow = { workspace = true }
ark-bn254 = { workspace = true }
ark-ec = { workspace = true }
ark-ed-on-bn254 = { workspace = true }
ark-ff = { workspace = true }
ark-serialize = { workspace = true }
ark-srs = { workspace = true }
ark-std = { workspace = true }
async-compatibility-layer = { workspace = true }
async-std = { workspace = true }
async-trait = { workspace = true }
blake3 = { workspace = true }
clap = { workspace = true }
cld = { workspace = true }
contract-bindings = { path = "../contract-bindings" }
derive_more = { workspace = true }
displaydoc = { version = "0.2.3", default-features = false }
es-version = { workspace = true }
ethers = { workspace = true }
futures = { workspace = true }
hotshot-contract-adapter = { workspace = true }
hotshot-orchestrator = { workspace = true }
hotshot-stake-table = { workspace = true }
hotshot-types = { workspace = true }
itertools = { workspace = true }
jf-crhf = { workspace = true }
jf-pcs = { workspace = true }
jf-plonk = { workspace = true }
jf-relation = { workspace = true }
jf-rescue = { workspace = true, features = ["gadgets"] }
jf-signature = { workspace = true, features = ["schnorr", "bls", "gadgets"] }
jf-utils = { workspace = true }
rand_chacha = { workspace = true }
reqwest = { workspace = true }
sequencer-utils = { path = "../utils" }
serde = { workspace = true }
snafu = { workspace = true }
surf-disco = { workspace = true }
tagged-base64 = { workspace = true }
tide-disco = { workspace = true }
time = { workspace = true }
toml = "0.8"
tracing = { workspace = true }
url = { workspace = true }
vbs = { workspace = true }

[features]
default = ["parallel"]
std = ["ark-std/std", "ark-ff/std"]
parallel = ["jf-signature/parallel", "jf-utils/parallel", "ark-ff/parallel"]
