[package]
name = "hotshot-state-prover"
description = "Generate state update proof for HotShot light client"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[features]
default = ["parallel"]
std = ["ark-std/std", "ark-ff/std"]
parallel = ["jf-signature/parallel", "jf-utils/parallel", "ark-ff/parallel"]

[dependencies]
alloy = { workspace = true }
anyhow = { workspace = true }
ark-bn254 = { workspace = true }
ark-ec = { workspace = true }
ark-ed-on-bn254 = { workspace = true }
ark-ff = { workspace = true }
ark-serialize = { workspace = true }
ark-srs = { workspace = true }
ark-std = { workspace = true }
clap = { workspace = true }
displaydoc = { version = "0.2.3", default-features = false }
espresso-contract-deployer = { path = "../contracts/rust/deployer" }
espresso-types = { path = "../types" }
futures = { workspace = true }
hotshot-contract-adapter = { workspace = true }
hotshot-query-service = { workspace = true }
hotshot-task-impls = { workspace = true }
hotshot-types = { workspace = true }
itertools = { workspace = true }
jf-crhf = { workspace = true }
jf-pcs = { workspace = true }
jf-plonk = { workspace = true }
# Dependencies below are for LCV1 backward compatibility
jf-plonk-compat = { package = "jf-plonk", git = "https://github.com/EspressoSystems/jellyfish", branch = "jf-relation-v0.5.0-compat", features = [
    "std",
] }
jf-relation = { workspace = true }
jf-relation-compat = { package = "jf-relation", git = "https://github.com/EspressoSystems/jellyfish", branch = "jf-relation-v0.5.0-compat", features = [
    "std",
] }
jf-rescue = { workspace = true, features = ["gadgets"] }
jf-rescue-compat = { package = "jf-rescue", git = "https://github.com/EspressoSystems/jellyfish", branch = "jf-relation-v0.5.0-compat", features = [
    "gadgets",
] }
jf-signature = { workspace = true, features = ["schnorr", "bls", "gadgets"] }
jf-signature-compat = { package = "jf-signature", git = "https://github.com/EspressoSystems/jellyfish", branch = "jf-relation-v0.5.0-compat", features = [
    "schnorr", "bls", "gadgets",
] }
jf-utils = { workspace = true }
reqwest = { workspace = true }
sequencer-utils = { path = "../utils" }
serde = { workspace = true }
surf-disco = { workspace = true }
tide-disco = { workspace = true }
time = { workspace = true }
tokio = { workspace = true }
toml = "0.8"
tracing = { workspace = true }
url = { workspace = true }
vbs = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
sequencer-utils = { path = "../utils", features = ["testing"] }
test-log = { workspace = true }

[lints]
workspace = true

