//! Axum glue for serving the wire protocol.
//!
//! Everything a service needs regardless of its routes: content-negotiated responses,
//! request-body decoding, the healthcheck response shapes, the permissive CORS layer, and one
//! correct way to drive a WebSocket stream endpoint. Services bring their own error envelope as a
//! [`WireError`] and share everything else here, so none of them needs to depend on another
//! service's API crate.

use axum::{
    Json,
    extract::{
        DefaultBodyLimit,
        ws::{CloseFrame, Message, WebSocket, close_code},
    },
    http::{HeaderMap, StatusCode, header},
    response::{IntoResponse, Response},
};
use futures::{StreamExt, stream::BoxStream};
use serde::{Serialize, de::DeserializeOwned};
use tower_http::cors::{Any, CorsLayer};

use crate::{
    body::{DecodeFailure, WireVersion, encode_body},
    content_type::ContentType,
    error::WireError,
    health::{AppHealth, HealthStatus},
    ws::{encode_binary_frame, encode_text_frame},
};

/// Encode a successful response body, negotiating VBS binary vs JSON from the `Accept` header.
pub fn encode_ok<E: WireError, T: Serialize>(headers: &HeaderMap, value: T) -> Response {
    let format = ContentType::negotiate(headers);
    match encode_body::<WireVersion, _>(format, &value) {
        Ok(bytes) => ([(header::CONTENT_TYPE, format.mime())], bytes).into_response(),
        Err(err) => encode_err::<E>(
            headers,
            E::catch_all(
                StatusCode::INTERNAL_SERVER_ERROR,
                format!("failed to serialize response: {err}"),
            ),
        ),
    }
}

/// Encode an error response using the same content negotiation as [`encode_ok`].
pub fn encode_err<E: WireError>(headers: &HeaderMap, err: E) -> Response {
    let status = err.status();
    let format = ContentType::negotiate(headers);
    match encode_body::<WireVersion, _>(format, &err) {
        Ok(bytes) => (status, [(header::CONTENT_TYPE, format.mime())], bytes).into_response(),
        // The envelope itself failed to serialize; fall back to JSON so the client at least
        // sees the status and a body (axum's `Json` degrades to a plain 500 if even that fails).
        Err(_) => (status, Json(err)).into_response(),
    }
}

pub fn respond<E: WireError, T: Serialize>(headers: &HeaderMap, result: Result<T, E>) -> Response {
    match result {
        Ok(value) => encode_ok::<E, _>(headers, value),
        Err(err) => encode_err(headers, err),
    }
}

/// Decode a request body: VBS for `application/octet-stream`, JSON for `application/json`.
/// Content types are matched by media-type essence so parameters (e.g. a charset) are tolerated.
pub fn decode_body<T: DeserializeOwned>(
    headers: &HeaderMap,
    body: &[u8],
) -> Result<T, DecodeFailure> {
    let content_type = headers
        .get(header::CONTENT_TYPE)
        .and_then(|v| v.to_str().ok());
    crate::body::decode_body::<WireVersion, T>(content_type, body)
}

/// App-level `/healthcheck` response, in JSON or vbs binary depending on `Accept`.
///
/// Reports [`AppHealth`] with no per-module entries, the shape every service with at least one
/// registered module has always served.
pub fn healthcheck_response(headers: &HeaderMap) -> Response {
    encode_health(headers, &AppHealth::default())
}

/// Per-module `/healthcheck` response: a bare [`HealthStatus`], the shape served for a module
/// without an explicit healthcheck handler.
pub fn module_healthcheck_response(headers: &HeaderMap) -> Response {
    encode_health(headers, &HealthStatus::Available)
}

pub const MAX_REQUEST_BODY_BYTES: usize = 128 * 1024 * 1024;

/// Only for routers whose bodies carry transactions; everything else keeps axum's 2 MiB default.
pub fn body_limit_layer() -> DefaultBodyLimit {
    DefaultBodyLimit::max(MAX_REQUEST_BODY_BYTES)
}

/// Permissive CORS: allow any origin, method, and headers on every response.
///
/// Apply it as the outermost layer, so it also covers responses generated by middleware rather
/// than a handler (a connection limit's 429 would otherwise skip it).
///
/// `allow_methods` and `allow_headers` are only echoed on the `OPTIONS` preflight, which is where
/// a browser reads them; `allow_origin` goes out on every response.
pub fn cors_layer() -> CorsLayer {
    CorsLayer::new()
        .allow_methods(Any)
        .allow_headers(Any)
        .allow_origin(Any)
}

/// Forwards `stream` over `socket` in the format negotiated by [`ContentType::negotiate`] until
/// the stream ends or the client disconnects, then performs the close handshake. Production
/// stream consumers default to `Accept: application/octet-stream` and expect VBS-encoded
/// `Message::Binary` frames.
///
/// This is the one shared way to serve a socket stream endpoint; hand-rolled write-only loops
/// leak the task and its data-source subscription whenever a client disconnects while the stream
/// is quiet.
///
/// Binary frames are framed with [`WireVersion`], like request and response bodies.
///
/// A stream that runs to completion closes with no close code. An item that fails to encode ends
/// the stream with close code 1011 (internal error), so a client can tell a server-side bug from
/// end-of-stream.
pub async fn drive_ws_stream<T: Serialize>(
    mut socket: WebSocket,
    stream: BoxStream<'static, T>,
    format: ContentType,
) {
    futures::pin_mut!(stream);
    let mut close = None;
    loop {
        // Also poll the client side: a disconnect must end this task even while the stream is
        // quiet, or the socket's connection slot and the stream task leak until the next send.
        let item = tokio::select! {
            item = stream.next() => item,
            msg = socket.recv() => match msg {
                None | Some(Err(_)) | Some(Ok(Message::Close(_))) => return,
                Some(Ok(_)) => continue,
            },
        };
        let Some(item) = item else { break };
        let frame = match format {
            ContentType::Binary => encode_binary_frame::<WireVersion, _>(&item)
                .map(|bytes| Message::Binary(bytes.into())),
            ContentType::Json => encode_text_frame(&item).map(|json| Message::Text(json.into())),
        };
        let msg = match frame {
            Ok(msg) => msg,
            Err(err) => {
                tracing::warn!(%err, "websocket stream item failed to encode, closing stream");
                // A fixed reason, not the error text: a close frame's reason is capped at 123
                // bytes and clients reject a longer one as a protocol error.
                close = Some(CloseFrame {
                    code: close_code::ERROR,
                    reason: "failed to encode stream item".into(),
                });
                break;
            },
        };
        if socket.send(msg).await.is_err() {
            return;
        }
    }
    // Close handshake, like the socket handlers before the axum migration. Without it, dropping
    // the socket resets the connection and clients see an error instead of end-of-stream. Finite
    // streams rely on a clean close to signal completion.
    _ = socket.send(Message::Close(close)).await;
}

/// Binds `url`'s host and port (falling back to the scheme's default port) and serves `router`
/// until the returned handle is aborted.
///
/// # Panics
/// If `url` has no port and its scheme has no default. Bind and serve failures happen on the
/// spawned task, so they abort that task rather than the caller: the handle resolves to a join
/// error and the server never comes up.
pub fn spawn_serve(url: &url::Url, router: axum::Router) -> tokio::task::JoinHandle<()> {
    let addr = format!(
        "{}:{}",
        url.host_str().unwrap_or("0.0.0.0"),
        url.port_or_known_default()
            .expect("server URL must carry a port or a scheme with a default")
    );
    tokio::spawn(async move {
        let listener = tokio::net::TcpListener::bind(&addr)
            .await
            .unwrap_or_else(|err| panic!("failed to bind listener on {addr}: {err}"));
        axum::serve(listener, router)
            .await
            .expect("server exited with an error");
    })
}

fn encode_health<T: Serialize>(headers: &HeaderMap, value: &T) -> Response {
    let format = ContentType::negotiate(headers);
    match encode_body::<WireVersion, _>(format, value) {
        Ok(bytes) => ([(header::CONTENT_TYPE, format.mime())], bytes).into_response(),
        Err(err) => (StatusCode::INTERNAL_SERVER_ERROR, err.to_string()).into_response(),
    }
}

#[cfg(test)]
mod tests {
    use axum::http::HeaderValue;
    use serde::Deserialize;
    use tokio_tungstenite::tungstenite;
    use vbs::{BinarySerializer, Serializer, version::StaticVersion};

    use super::*;

    #[derive(Debug, Serialize, Deserialize, PartialEq, thiserror::Error)]
    #[error("Error {status}: {message}")]
    struct TestError {
        status: u16,
        message: String,
    }

    impl WireError for TestError {
        fn status(&self) -> StatusCode {
            StatusCode::from_u16(self.status).unwrap_or(StatusCode::INTERNAL_SERVER_ERROR)
        }

        fn catch_all(status: StatusCode, message: String) -> Self {
            Self {
                status: status.as_u16(),
                message,
            }
        }
    }

    fn headers(name: header::HeaderName, value: &str) -> HeaderMap {
        let mut headers = HeaderMap::new();
        headers.insert(name, HeaderValue::from_str(value).unwrap());
        headers
    }

    async fn body_bytes(resp: Response) -> Vec<u8> {
        axum::body::to_bytes(resp.into_body(), usize::MAX)
            .await
            .unwrap()
            .to_vec()
    }

    #[tokio::test]
    async fn encode_negotiates_binary_and_json() {
        let binary = headers(header::ACCEPT, "application/octet-stream");
        let resp = encode_ok::<TestError, _>(&binary, 42u64);
        assert_eq!(resp.status(), StatusCode::OK);
        assert_eq!(
            resp.headers().get(header::CONTENT_TYPE).unwrap(),
            "application/octet-stream"
        );
        let bytes = body_bytes(resp).await;
        let decoded: u64 = Serializer::<StaticVersion<0, 1>>::deserialize(&bytes).unwrap();
        assert_eq!(decoded, 42);

        let resp = encode_ok::<TestError, _>(&HeaderMap::new(), 42u64);
        assert_eq!(resp.status(), StatusCode::OK);
        assert_eq!(String::from_utf8(body_bytes(resp).await).unwrap(), "42");
    }

    #[tokio::test]
    async fn errors_carry_status_and_envelope() {
        let err = TestError {
            status: 404,
            message: "no such thing".into(),
        };
        let resp = encode_err(&HeaderMap::new(), err);
        assert_eq!(resp.status(), StatusCode::NOT_FOUND);
        let decoded: TestError = serde_json::from_slice(&body_bytes(resp).await).unwrap();
        assert_eq!(decoded.message, "no such thing");

        let binary = headers(header::ACCEPT, "application/octet-stream");
        let err = TestError {
            status: 404,
            message: "no such thing".into(),
        };
        let resp = encode_err(&binary, err);
        assert_eq!(resp.status(), StatusCode::NOT_FOUND);
        let decoded: TestError =
            Serializer::<StaticVersion<0, 1>>::deserialize(&body_bytes(resp).await).unwrap();
        assert_eq!(decoded.status, 404);
    }

    #[derive(Clone)]
    enum Item {
        Encodable(u64),
        Unencodable,
    }

    impl Serialize for Item {
        fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
        where
            S: serde::Serializer,
        {
            match self {
                Item::Encodable(n) => n.serialize(serializer),
                Item::Unencodable => Err(serde::ser::Error::custom(
                    "an error message long enough that it would not fit in a close frame's \
                     reason, which the protocol caps at 123 bytes",
                )),
            }
        }
    }

    struct Received {
        data_frames: usize,
        close: Option<tungstenite::protocol::CloseFrame>,
    }

    async fn stream_over_socket(items: Vec<Item>, format: ContentType) -> Received {
        let app = axum::Router::new().route(
            "/",
            axum::routing::get(move |ws: axum::extract::WebSocketUpgrade| async move {
                let stream = futures::stream::iter(items).boxed();
                ws.on_upgrade(move |socket| drive_ws_stream(socket, stream, format))
            }),
        );
        let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
        let addr = listener.local_addr().unwrap();
        tokio::spawn(async move { axum::serve(listener, app).await.unwrap() });

        let (mut ws, _) = tokio_tungstenite::connect_async(format!("ws://{addr}/"))
            .await
            .unwrap();
        let mut data_frames = 0;
        loop {
            match ws.next().await.unwrap().unwrap() {
                tungstenite::Message::Text(_) | tungstenite::Message::Binary(_) => data_frames += 1,
                tungstenite::Message::Close(close) => return Received { data_frames, close },
                tungstenite::Message::Ping(_)
                | tungstenite::Message::Pong(_)
                | tungstenite::Message::Frame(_) => {},
            }
        }
    }

    #[tokio::test]
    async fn encode_failure_closes_with_internal_error() {
        for format in [ContentType::Json, ContentType::Binary] {
            let items = Vec::from([Item::Encodable(1), Item::Unencodable, Item::Encodable(2)]);
            let Received { data_frames, close } = stream_over_socket(items, format).await;
            assert_eq!(data_frames, 1, "{format:?}");
            let close = close.expect("an encode failure must send a close code");
            assert_eq!(
                close.code,
                tungstenite::protocol::frame::coding::CloseCode::Error
            );
        }
    }

    #[tokio::test]
    async fn completed_stream_closes_cleanly() {
        let items = Vec::from([Item::Encodable(1), Item::Encodable(2)]);
        let Received { data_frames, close } = stream_over_socket(items, ContentType::Json).await;
        assert_eq!(data_frames, 2);
        assert!(close.is_none());
    }

    #[test]
    fn decode_matches_content_type_by_essence() {
        let json = headers(header::CONTENT_TYPE, "application/json; charset=utf-8");
        let decoded: u64 = decode_body(&json, b"42").unwrap();
        assert_eq!(decoded, 42);

        let binary = headers(header::CONTENT_TYPE, "application/octet-stream");
        let bytes = Serializer::<StaticVersion<0, 1>>::serialize(&42u64).unwrap();
        let decoded: u64 = decode_body(&binary, &bytes).unwrap();
        assert_eq!(decoded, 42);

        assert!(matches!(
            decode_body::<u64>(&HeaderMap::new(), b"42"),
            Err(DecodeFailure::UnsupportedContentType)
        ));
        assert!(matches!(
            decode_body::<u64>(&json, b"not json"),
            Err(DecodeFailure::Json(_))
        ));
        assert!(matches!(
            decode_body::<u64>(&binary, b""),
            Err(DecodeFailure::Binary(_))
        ));
    }
}
