//! Pins the v2 wire encoding to canonical protoJSON (generated by pbjson): lowerCamelCase
//! field names, 64-bit integers as decimal strings, and default values omitted. Deserialization
//! accepts both camelCase and the original proto field names.
//!
//! Changing any expectation here is a breaking change for every v2 REST client.
//!
//! protoJSON also encodes `bytes` as base64 and flattens a `oneof` into its parent, but no
//! message in the served surface has either, so nothing here pins them. An endpoint that
//! introduces one should add the case.

use espresso_api::proto;
use serde_json::json;

#[test]
fn u64_serializes_as_string() {
    let response = proto::BlockHeightResponse { height: u64::MAX };
    assert_eq!(
        serde_json::to_value(response).unwrap(),
        json!({"height": "18446744073709551615"})
    );
}

#[test]
fn field_names_are_camel_case_and_defaults_are_omitted() {
    let response = proto::NodeKeysResponse {
        eth_account: None,
        consensus_key: Some(proto::BlsPublicKey {
            key: "BLS_VER_KEY~abc".to_string(),
        }),
        state_ver_key: None,
        x25519_key: None,
    };
    assert_eq!(
        serde_json::to_value(response).unwrap(),
        json!({"consensusKey": {"key": "BLS_VER_KEY~abc"}})
    );
}

#[test]
fn deserialize_accepts_both_field_name_forms_and_quoted_numbers() {
    let snake: proto::NodeKeysResponse =
        serde_json::from_value(json!({"eth_account": "0xabc", "x25519_key": "X~def"})).unwrap();
    let camel: proto::NodeKeysResponse =
        serde_json::from_value(json!({"ethAccount": "0xabc", "x25519Key": "X~def"})).unwrap();
    assert_eq!(snake, camel);
    assert_eq!(snake.eth_account.as_deref(), Some("0xabc"));

    let quoted: proto::BlockHeightResponse =
        serde_json::from_value(json!({"height": "7"})).unwrap();
    let bare: proto::BlockHeightResponse = serde_json::from_value(json!({"height": 7})).unwrap();
    assert_eq!(quoted, bare);
    assert_eq!(quoted.height, 7);
}

// The generated REST handlers extract requests with `axum::extract::Query`, which drives
// these same impls through serde_urlencoded rather than serde_json.
#[test]
fn empty_query_string_decodes_parameterless_requests() {
    serde_urlencoded::from_str::<proto::GetBlockHeightRequest>("").unwrap();
    serde_urlencoded::from_str::<proto::GetNodeKeysRequest>("").unwrap();
    serde_urlencoded::from_str::<proto::GetTotalMintedSupplyRequest>("").unwrap();
}

#[test]
fn unknown_query_parameters_are_rejected() {
    serde_urlencoded::from_str::<proto::GetBlockHeightRequest>("height=5").unwrap_err();
}
