//! Pins the v2 wire encoding to canonical protoJSON (generated by pbjson): lowerCamelCase
//! field names, 64-bit integers as decimal strings, and default values omitted. Deserialization
//! accepts both camelCase and the original proto field names.
//!
//! Changing any expectation here is a breaking change for every v2 REST client.
//!
//! protoJSON also encodes `bytes` as base64 and flattens a `oneof` into its parent, but no
//! message in the served surface has either, so nothing here pins them. An endpoint that
//! introduces one should add the case, as the node service did for enums and repeated fields.

use espresso_api::proto;
use serde_json::json;

#[test]
fn u64_serializes_as_string() {
    let response = proto::BlockHeightResponse { height: u64::MAX };
    assert_eq!(
        serde_json::to_value(response).unwrap(),
        json!({"height": "18446744073709551615"})
    );
}

#[test]
fn field_names_are_camel_case_and_defaults_are_omitted() {
    let response = proto::NodeKeysResponse {
        eth_account: None,
        consensus_key: Some(proto::BlsPublicKey {
            key: "BLS_VER_KEY~abc".to_string(),
        }),
        state_ver_key: None,
        x25519_key: None,
    };
    assert_eq!(
        serde_json::to_value(response).unwrap(),
        json!({"consensusKey": {"key": "BLS_VER_KEY~abc"}})
    );
}

#[test]
fn deserialize_accepts_both_field_name_forms_and_quoted_numbers() {
    let snake: proto::NodeKeysResponse =
        serde_json::from_value(json!({"eth_account": "0xabc", "x25519_key": "X~def"})).unwrap();
    let camel: proto::NodeKeysResponse =
        serde_json::from_value(json!({"ethAccount": "0xabc", "x25519Key": "X~def"})).unwrap();
    assert_eq!(snake, camel);
    assert_eq!(snake.eth_account.as_deref(), Some("0xabc"));

    let quoted: proto::BlockHeightResponse =
        serde_json::from_value(json!({"height": "7"})).unwrap();
    let bare: proto::BlockHeightResponse = serde_json::from_value(json!({"height": 7})).unwrap();
    assert_eq!(quoted, bare);
    assert_eq!(quoted.height, 7);
}

// The generated REST handlers extract requests with `axum::extract::Query`, which drives
// these same impls through serde_urlencoded rather than serde_json.
#[test]
fn empty_query_string_decodes_parameterless_requests() {
    serde_urlencoded::from_str::<proto::GetBlockHeightRequest>("").unwrap();
    serde_urlencoded::from_str::<proto::GetNodeKeysRequest>("").unwrap();
    serde_urlencoded::from_str::<proto::GetTotalMintedSupplyRequest>("").unwrap();
    serde_urlencoded::from_str::<proto::GetSyncStatusRequest>("").unwrap();
}

#[test]
fn query_parameters_decode_optional_numbers() {
    let full: proto::GetTransactionCountRequest =
        serde_urlencoded::from_str("from=100&to=200&namespace=1").unwrap();
    assert_eq!(
        full,
        proto::GetTransactionCountRequest {
            from: Some(100),
            to: Some(200),
            namespace: Some(1),
        }
    );

    let partial: proto::GetTransactionCountRequest = serde_urlencoded::from_str("to=200").unwrap();
    assert_eq!(partial.to, Some(200));
    assert_eq!(partial.from, None);

    serde_urlencoded::from_str::<proto::GetTransactionCountRequest>("from=abc").unwrap_err();
}

#[test]
fn unknown_query_parameters_are_rejected() {
    serde_urlencoded::from_str::<proto::GetBlockHeightRequest>("height=5").unwrap_err();
}

#[test]
fn enums_serialize_as_value_names_and_repeated_fields_as_arrays() {
    let response = proto::ResourceSyncStatus {
        missing: 0,
        ranges: vec![proto::SyncStatusRange {
            start: 0,
            end: 10,
            status: proto::SyncStatus::Present.into(),
        }],
    };
    // `missing` and `start` are zero, so a client has to read an absent field as zero.
    assert_eq!(
        serde_json::to_value(response).unwrap(),
        json!({"ranges": [{"end": "10", "status": "SYNC_STATUS_PRESENT"}]})
    );
}

#[test]
fn deserialize_accepts_enum_names_and_numbers() {
    let named: proto::SyncStatusRange =
        serde_json::from_value(json!({"status": "SYNC_STATUS_PRUNED"})).unwrap();
    let numbered: proto::SyncStatusRange = serde_json::from_value(json!({"status": 3})).unwrap();
    assert_eq!(named, numbered);
    assert_eq!(named.status(), proto::SyncStatus::Pruned);
}
