[package]
name = "hotshot-utils"
version = { workspace = true }
edition = { workspace = true }
description = "Utils"
license = "MIT"

[dependencies]
tracing = { workspace = true }

[lints]
workspace = true
