name: Espresso Docker Image

inputs:
  file:
    required: true
    type: string
  images:
    required: true
    type: string
  platforms:
    required: true
    type: string
  push:
    required: true
    type: boolean

outputs:
  digest:
    value: "${{ steps.build.outputs.digest }}"

runs:
  using: composite
  steps:

    - name: Generate docker metadata
      uses: docker/metadata-action@v5
      id: metadata
      with:
        images: ${{ inputs.images }}

    - name: Build and push docker
      uses: docker/build-push-action@v5
      id: build
      with:
        context: .
        file: ${{ inputs.file }}
        platforms: ${{ inputs.platforms }}
        target: ${{ inputs.target }}
        tags: ${{ steps.metadata.outputs.tags }}
        labels: ${{ steps.metadata.outputs.labels  }}
        push: ${{ inputs.push }}
