name: Free Disk Space
description: Free up disk space on GitHub runners using rmz for fast deletion
runs:
  using: composite
  steps:
    - uses: taiki-e/install-action@cargo-binstall
    - name: Free disk space
      shell: bash
      run: |
        cargo binstall -y rmz
        sudo mv /home/runner/.cargo/bin/rmz /usr/local/bin/rmz

        echo "Available storage before:"
        sudo df -h
        echo
        sudo rmz -f /usr/share/dotnet
        sudo rmz -f /usr/share/swift
        sudo rmz -f /usr/share/gradle-*
        sudo rmz -f /usr/share/az_*
        sudo rmz -f /usr/local/lib/android
        sudo rmz -f /opt/ghc
        sudo rmz -f /opt/az
        sudo rmz -f /opt/pipx
        sudo rmz -f /opt/google
        sudo rmz -f /opt/microsoft
        echo "Available storage after:"
        sudo df -h
        echo
