//! `proposal.toml` schema: generated by `deploy`, validated by `deploy verify-proposal`.

use alloy::primitives::{Address, B256, U256};
use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct ProposalToml {
    /// Contract kind in kebab-case (e.g. "stake-table-v3").
    pub contract: String,
    /// Network name (e.g. "decaf", "mainnet").
    pub network: String,
    /// EVM chain ID.
    pub chain_id: u64,
    /// Proxy contract address.
    pub proxy: Address,
    /// New implementation address (from the inner upgradeToAndCall).
    #[serde(rename = "impl")]
    pub new_impl: Address,
    /// Timelock contract address (outer_to from the proposal).
    pub timelock: Address,
    /// Salt used in the timelock operation.
    pub salt: B256,
    /// Timelock delay in seconds.
    pub delay: u64,
    /// Predecessor (zero for independent operations).
    pub predecessor: B256,

    pub schedule: PhaseToml,
    pub execute: PhaseToml,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct PhaseToml {
    /// Safe multisig address that signs this phase.
    pub safe: Address,
    /// Safe nonce at proposal-generation time.
    pub nonce: u64,
    /// EIP-712 domain separator hash.
    pub domain: B256,
    /// EIP-712 message hash.
    pub message: B256,
    /// EIP-712 safe_tx hash (what the Ledger displays).
    pub safe_tx: B256,
}

impl ProposalToml {
    pub fn load(dir: &std::path::Path) -> Result<Self> {
        let p = dir.join("proposal.toml");
        let text =
            std::fs::read_to_string(&p).with_context(|| format!("cannot read {}", p.display()))?;
        toml::from_str(&text).with_context(|| format!("failed to parse {}", p.display()))
    }

    pub fn write(&self, dir: &std::path::Path) -> Result<()> {
        let p = dir.join("proposal.toml");
        let text = toml::to_string_pretty(self).context("failed to serialize proposal.toml")?;
        // Prepend generation notice.
        let full = format!(
            "# Generated by `deploy`; validated by `deploy verify-proposal` and CI. Do not \
             hand-edit.\n{text}"
        );
        std::fs::write(&p, full).with_context(|| format!("failed to write {}", p.display()))
    }

    /// Convert the TOML delay (u64 seconds) to a U256 for comparison with on-chain values.
    pub fn delay_u256(&self) -> U256 {
        U256::from(self.delay)
    }

    /// Convert the TOML predecessor B256 field.
    pub fn predecessor_b256(&self) -> B256 {
        self.predecessor
    }
}
