[profile.default]
slow-timeout = "2m"
default-filter = 'not (test(slow_) | package(tests))'
retries = 2

[profile.slow]
slow-timeout = "2m"
default-filter = 'test(slow_)'
retries = 2

[profile.all]
slow-timeout = "2m"
default-filter = 'all()'
retries = 2

[profile.integration]
slow-timeout = "2m"
default-filter = 'package(tests)'
retries = 2
