[profile.default]
# Kill tests after 3 periods of 2m, because they are probably hanging
slow-timeout = { period = "2m", terminate-after = 3 }
default-filter = 'not (test(slow_) | package(tests))'
retries = 2
# TODO: ensure tests can run in parallel
threads-required = 'num-test-threads'

[[profile.default.overrides]]
# These tests are fast if they work (usually about 150ms) but sometimes they
# hang, especially when running Concurrently with other tests. Kill after a
# while and retry up to 10 times to avoid failing the test suite.
filter = """
test(test_process_client_handling_stream_subscribe_node_identity) |
test(test_process_client_handling_stream_subscribe_voters)
"""
slow-timeout = { period = "2s", terminate-after = 1 }
retries  = 10

# The restart tests run an entire sequencing network, and so are quite resource intensive.
[[profile.default.overrides]]
filter = 'test(slow_test_restart)'
threads-required = 'num-cpus'

[profile.slow]
slow-timeout = "2m"
default-filter = 'test(slow_)'
retries = 2

[profile.all]
slow-timeout = "2m"
default-filter = 'all()'
retries = 2

[profile.integration]
slow-timeout = "2m"
default-filter = 'package(tests)'
retries = 2
