#!/usr/bin/env bash
set -euxo pipefail

# process
# - start the network on main tag
# - upgrade builder
# - for each node
#   - upgrade
#   - assert progress

# Note: explicitly want to re-use volumes where postgres/sqlite/filesystem nodes store data

# currently running on mainnet
base_tag=20250228-patch3

# do some cleanup
just down -v || true
docker stop $(docker ps -aq) || true
docker rm $(docker ps -aq) || true

# inject some env vars that since changed in the local demo
export ESPRESSO_SEQUENCER_LIGHT_CLIENT_PROXY_ADDRESS=0x0c8e79f3534b00d9a3d4a856b665bf4ebc22f2ba
export ESPRESSO_SEQUENCER_PERMISSIONED_PROVER=0x14dc79964da2c08b23698b3d3cc7ca32193d9955
export ESPRESSO_SEQUENCER_PERMISSIONED_STAKE_TABLE_ADDRESS=0x8ce361602b935680e8dec218b820ff5056beb7af

# start the demo on mainnet version
env DOCKER_TAG=$base_tag just demo --wait

scripts/smoke-test-demo

# first upgrade the builder and the first sequencer node
# docker compose stop permissionless-builder
# env DOCKER_TAG=main docker compose up --no-deps permissionless-builder --force-recreate --wait

# scripts/smoke-test-demo # this will potentially work once at first but we soon only get empty blocks
# scripts/smoke-test-demo # XXX will fail: no new txns finalized
# builder now has event stream errors:
# run: docker logs espresso-network-permissionless-builder-1
# WARN marketplace_builder_shared::utils::event_service_wrapper: Error in event stream err=Custom { message: "invalid binary: tag for enum is not valid, found 55
# WARN marketplace_builder_shared::utils::event_service_wrapper: Error in event stream err=Custom { message: "invalid binary: invalid value: integer `88`, expected variant index 0 <= i < 2

# upgrade sequencer0 binary
docker compose stop sequencer0
env DOCKER_TAG=main docker compose up --no-deps sequencer0 --force-recreate --wait

docker compose stop permissionless-builder
env DOCKER_TAG=$base_tag HOTSHOT_EVENTS_VERSION=v0 \
    docker compose up --no-deps permissionless-builder --force-recreate --wait

# submit transactions will have exited due to closed stream
env DOCKER_TAG=$base_tag docker compose up --no-deps submit-transactions-public --wait
env DOCKER_TAG=$base_tag docker compose up --no-deps submit-transactions-private --wait

# Now the mainnet builder doesn't work because if we specify the /v0 url for the
# event stream, then /healthcheck doesn't work, /healthcheck only works for the
# bare URL, without version.
#

# we now get "invalid builder signature" errors in sequencer1 logs

# scripts/smoke-test-demo

# assert sequencer 0 is running and making progress
