[package]
name = "builder"
description = "A standalone builder service"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow = { workspace = true }
async-broadcast = "0.7.0"
async-lock = "2.8"
async-compatibility-layer = { workspace = true }
async-std = { workspace = true }
clap = { workspace = true }
futures = { workspace = true }
jf-primitives = { workspace = true }
hotshot-types = { workspace = true }
hotshot = { workspace = true }
hotshot-orchestrator = { workspace = true }
hotshot-stake-table = { workspace = true }
hs-builder-api = { workspace = true }
hs-builder-core = { workspace = true }
sequencer = { path = "../sequencer" }
tracing = { workspace = true }
tide-disco = { workspace = true }
async-trait = { workspace = true }
# [[bin]]
