[route.account]
PATH = ["/:height/:view/account/:address"]
":height" = "Integer"
":view" = "Integer"
":address" = "Literal"
DOC = """
Get the fee account balance for `address`.

This endpoint can be used to catch up to the current state from a recent state by fetching the
balance (with proof) at the given block `:height` and `:view` number. `:height` and `:view` _must_
correspond! `:height` is provided to simplify lookups for backends where data is not indexed by
view.

This endpoint is intended to be used for catchup, so `:view` should be no older than the last
decided view.

Returns the account balance and a Merkle proof relative to the fee state root at the requested
height and view. If there is no entry for this account in the requested fee state (note: this is
distinct from the server _not knowing_ the entry for this account), the returned balance is 0 and
the proof is a Merkle _non-membership_ proof.

```
{
    "balance": "integer",
    "proof": { ... },
}
```
"""

[route.blocks]
PATH = ["/:height/:view/blocks"]
":height" = "Integer"
":view" = "Integer"
DOC = """
Get the blocks Merkle tree frontier.

This endpoint can be used to catch up to the current state from a recent state by fetching the
frontier at the given block `:height` and `:view` number. `:height` and `:view` _must_ correspond!
`:height` is provided to simplify lookups for backends where data is not indexed by view.

This endpoint is intended to be used for catchup, so `:view` should be no older than the last
decided view.

Returns the blocks Merkle tree frontier -- the path to the most recently appended leaf, relative to
root node at the requested block height and view.
"""
