[route.stake_table_current]
PATH = ["stake-table/current"]
DOC = "Get the stake table for the current epoch"

[route.stake_table]
PATH = ["stake-table/:epoch_number"]
":epoch_number" = "Integer"
DOC = "Get the stake table for the given epoch"

[route.get_validators]
PATH = ["validators/:epoch_number"]
":epoch_number" = "Integer"
DOC = "Get the validators map for the given epoch."

[route.get_all_validators]
PATH = ["all-validators/:epoch_number/:offset/:limit"]
":epoch_number" = "Integer"
":offset" = "Integer"
":limit" = "Integer"
DOC = "Get all the validators including the inactive ones for the given epoch."


[route.current_proposal_participation]
PATH = ["/current-proposal-participation"]
DOC = """
Get the mapping from leader key to participation rate.

Returns a map from BLS key to the fraction of views with key proposed properly as leader, as a floating point number.
"""

[route.previous_proposal_participation]
PATH = ["/previous-proposal-participation"]
DOC = """
Get the mapping from leader key to participation rate for the previous epoch.

Returns a map from BLS key to the fraction of views with key proposed properly as leader, as a floating point number.
"""
[route.get_block_reward]
PATH = ["block-reward", "block-reward/epoch/:epoch_number"]
":epoch_number" = "Integer"
DOC = "get the block reward"
