[route.current_version]
PATH = ["/current_version"]
METHOD = "GET"
DOC = "Get the current version for the node."

[route.chain_config]
PATH = ["/chain_config"]
METHOD = "GET"
DOC = "Get the chain_config for the node."

[route.api_version]
PATH = ["/api_version"]
METHOD = "GET"
DOC = "Get the API version for the node."

