[route.stake_table_current]
PATH = ["stake-table/current"]
DOC = "Get the stake table for the current epoch"

[route.stake_table]
PATH = ["stake-table/:epoch_number"]
":epoch_number" = "Integer"
DOC = "Get the stake table for the given epoch"

[route.get_validators]
PATH = ["validators/:epoch_number"]
":epoch_number" = "Integer"
DOC = "Get the validators map for the given epoch."

[route.incorrect_encoding_proof]
PATH = ["incorrect-encoding-proof/:block_number"]
":block_number" = "Integer"
DOC = "Generate a proof of incorrect encoding for the given block number."
