[route.version]
PATH = ["/current_version"]
METHOD = "GET"
DOC = "Get the version from the node's state."

[route.chain_config]
PATH = ["/chain_config"]
METHOD = "GET"
DOC = "Get the chain_config for the node's state."

[route.version]
PATH = ["/api_version"]
METHOD = "GET"
DOC = "Get the API version for the current node."

