[meta]
NAME = "hotshot_state_relay_server"
DESCRIPTION = "A relay server for storing and serving the light client states and their signatures"
FORMAT_VERSION = "0.1.0"

[route.poststatesignature]
PATH = ["state"]
METHOD = "POST"
DOC = """
Post a light client state and its signature for a given block height.
"""

[route.lateststate]
PATH = ["lateststate"]
METHOD = "GET"
DOC = """
Fetch the latest light client state who has enough corresponding Schnorr signatures collected,
as well as a list of those signatures.
"""

[route.getlateststate]
PATH = ["state"]
METHOD = "GET"
DOC = """
DEPRECATED!
Fetch the latest light client state who has enough corresponding Schnorr signatures collected,
as well as a list of those signatures.
"""


[route.postlegacystatesignature]
PATH = ["legacy-state"]
METHOD = "POST"
DOC = """
DEPRECATED!
Post a state and its signature for the legacy light client.
"""

[route.getlatestlegacystate]
PATH = ["legacy-state"]
METHOD = "GET"
DOC = """
DEPRECATED!
Fetch the latest state for the legacy light client.
"""