[package]
name = "serialization-api"
version.workspace = true
edition.workspace = true

[package.metadata]
# Mark as generated to prevent manual edits
generated = true

[dependencies]
axum = { workspace = true }
prost = { workspace = true }
serde = { workspace = true }
tonic = { workspace = true }
tonic-prost = { workspace = true }
tonic-rest = { workspace = true }

[build-dependencies]
tonic-prost-build = { workspace = true }
tonic-rest-build = { workspace = true }
