[package]
name = "hotshot_contract"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.12.0"
contract-bindings = { path = "../../contract-bindings" }
ethers = { version = "1.0.2", features = ["abigen"] }
ethers-providers = "2.0.0"
ethers-solc = "1.0.2"
hex = "0.4.3"
jf-primitives = { git = "https://github.com/EspressoSystems/jellyfish", rev = "546ed712867a7c4da79194eb2370c4e21ef0407f" }
sequencer-utils = { path = "../../utils" }
sha3 = { version = "0.10.5", default-features = false }
tokio = "1.26.0"

