rpc_url = "http://127.0.0.1:8545"
stake_table_address = "0x2a264f26859166c5bf3868a54593ee716aebc848"
espresso_url = "http://localhost:24000"

[signer]
mnemonic = "test test test test test test test test test test test junk"
account_index = 20
ledger = false
