name: Security audit
on:
  push:
    branches:
      - main
      - release-*
    tags:
      # YYYYMMDD
      - "20[0-9][0-9][0-1][0-9][0-3][0-9]*"
  pull_request:
    # For PRs we only want to fail if dependencies were changed.
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
  workflow_dispatch:
  # Run the audit job once a day on main.
  schedule:
    - cron: "0 0 * * *"
jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install capnproto
        uses: ./.github/actions/install-capnp
        
      # See https://github.com/rustsec/audit-check for docs
      - uses: rustsec/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
