name: Release build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: buildjet-16vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        run: rustup toolchain install stable --profile minimal

      - name: Use Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: build-${{ github.ref }}

      - name: Release build
        run: cargo build --release --all-targets
