name: Build

on:
  push:
    branches:
      - main
      - release-*
    tags:
      # YYYYMMDD
      - "20[0-9][0-9][0-1][0-9][0-3][0-9]*"
  schedule:
    - cron: "0 0 * * 1"
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  RUST_LOG: info,libp2p=off,node=error
  CARGO_TERM_COLOR: always
  DOCKER_PLATFORMS: ${{ github.event_name == 'pull_request' && 'linux/amd64' || 'linux/amd64,linux/arm64' }}

jobs:
  build:
    runs-on: buildjet-8vcpu-ubuntu-2204
    steps:
      - uses: rui314/setup-mold@v1

      - name: Install just command runner
        run: |
          sudo snap install --edge --classic just
          just --version

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Enable Rust Caching
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: v1-rust
          cache-provider: buildjet

      - name: Build
        # Build in release without `testing` feature, this should work without `hotshot_example` config.
        run: |
          cargo build --locked --release --workspace
      
      - name: Build sequencer-sqlite 
        run: cargo build --locked --release --manifest-path ./sequencer-sqlite/Cargo.toml --target-dir ./target

      - name: Build Espresso Dev Node
        # Espresso Dev Node currently requires testing feature, so it is built separately.
        run: |
          cargo build --locked --release --features "testing embedded-db" --bin espresso-dev-node

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: x86_64-unknown-linux-gnu-services
          path: |
            target/release/orchestrator
            target/release/cdn-broker
            target/release/cdn-marshal
            target/release/cdn-whitelist
            target/release/state-relay-server
            target/release/state-prover
            target/release/sequencer
            target/release/cli
            target/release/submit-transactions
            target/release/reset-storage
            target/release/utils
            target/release/deploy
            target/release/keygen
            target/release/permissionless-builder
            target/release/nasty-client
            target/release/espresso-dev-node
            target/release/pub-key
            target/release/update-permissioned-stake-table
            target/release/espresso-bridge
            target/release/marketplace-solver
            target/release/marketplace-builder
            target/release/node-metrics
            target/release/dev-rollup
            target/release/sequencer-sqlite

  build-arm:
    if: github.event_name != 'pull_request'
    runs-on: buildjet-8vcpu-ubuntu-2204-arm
    env:
      CARGO_BUILD_JOBS: '6'
    steps:
      - uses: rui314/setup-mold@v1

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Enable Rust Caching
        uses: Swatinem/rust-cache@v2
        with:
          cache-provider: buildjet

      - name: Build
        run: |
          cargo build --locked --release --workspace

      - name: Build sequencer-sqlite 
        run: cargo build --locked --release --manifest-path ./sequencer-sqlite/Cargo.toml --target-dir ./target

      - name: Build Espresso Dev Node
        # Espresso Dev Node currently requires testing feature, so it is built separately.
        run: |
          cargo build --locked --release --features "embedded-db testing" --bin espresso-dev-node

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: aarch64-unknown-linux-gnu-services
          path: |
            target/release/orchestrator
            target/release/cdn-broker
            target/release/cdn-marshal
            target/release/cdn-whitelist
            target/release/state-relay-server
            target/release/state-prover
            target/release/sequencer
            target/release/cli
            target/release/submit-transactions
            target/release/reset-storage
            target/release/utils
            target/release/deploy
            target/release/keygen
            target/release/permissionless-builder
            target/release/nasty-client
            target/release/update-permissioned-stake-table
            target/release/espresso-dev-node
            target/release/pub-key
            target/release/espresso-bridge
            target/release/marketplace-solver
            target/release/marketplace-builder
            target/release/node-metrics
            target/release/dev-rollup
            target/release/sequencer-sqlite

  build-dockers:
    runs-on: ubuntu-latest
    needs: [build, build-arm]
    # if build_arm is skipped, run this job anyway
    if: ${{ !(failure() || cancelled()) }}
    outputs:
      sequencer-tag: ${{ steps.sequencer.outputs.tags }}
      cdn-broker-tag: ${{ steps.cdn-broker.outputs.tags }}
      cdn-marshal-tag: ${{ steps.cdn-marshal.outputs.tags }}
      cdn-whitelist-tag: ${{ steps.cdn-whitelist.outputs.tags }}
      state-relay-server-tag: ${{ steps.state-relay-server.outputs.tags }}
      prover-service-tag: ${{ steps.prover-service.outputs.tags }}
      orchestrator-tag: ${{ steps.orchestrator.outputs.tags }}
      submit-transactions-tag: ${{ steps.submit-transactions.outputs.tags }}
      deploy-tag: ${{ steps.deploy.outputs.tags }}
      builder-tag: ${{ steps.builder.outputs.tags }}
      nasty-client-tag: ${{ steps.nasty-client.outputs.tags }}
      update-permissioned-stake-table-tag: ${{ steps.update-permissioned-stake-table.outputs.tags }}
      espresso-dev-node-tag: ${{ steps.espresso-dev-node.outputs.tags }}
      bridge-tag: ${{ steps.bridge.outputs.tags }}
      marketplace-solver-tag: ${{ steps.marketplace-solver.outputs.tags }}
      marketplace-builder-tag: ${{ steps.marketplace-builder.outputs.tags }}
      node-validator-tag: ${{ steps.node-validator.outputs.tags }}
      dev-rollup-tag: ${{ steps.dev-rollup.outputs.tags }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download executables AMD
        uses: actions/download-artifact@v4
        with:
          name: x86_64-unknown-linux-gnu-services
          path: target/amd64/release

      - name: Download executables ARM
        if: github.event_name != 'pull_request'
        uses: actions/download-artifact@v4
        with:
          name: aarch64-unknown-linux-gnu-services
          path: target/arm64/release

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          # Temporary fix (See https://github.com/docker/setup-qemu-action/issues/198)
          image: tonistiigi/binfmt:qemu-v7.0.0-28

      - name: Setup Docker BuildKit (buildx)
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Container Repo
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build sequencer docker image
        uses: ./.github/actions/docker-image
        with:
          file: ./docker/sequencer.Dockerfile
          images: ghcr.io/espressosystems/espresso-sequencer/sequencer
          platforms: ${{ env.DOCKER_PLATFORMS }}
          push: ${{ github.event_name != 'pull_request' }}

      - name: Build cdn-broker docker image
        uses: ./.github/actions/docker-image
        with:
          file: ./docker/cdn-broker.Dockerfile
          images: ghcr.io/espressosystems/espresso-sequencer/cdn-broker
          platforms: ${{ env.DOCKER_PLATFORMS }}
          push: ${{ github.event_name != 'pull_request' }}

      - name: Build cdn-marshal docker image
        uses: ./.github/actions/docker-image
        with:
          file: ./docker/cdn-marshal.Dockerfile
          images: ghcr.io/espressosystems/espresso-sequencer/cdn-marshal
          platforms: ${{ env.DOCKER_PLATFORMS }}
          push: ${{ github.event_name != 'pull_request' }}

      - name: Build cdn-whitelist docker image
        uses: ./.github/actions/docker-image
        with:
          file: ./docker/cdn-whitelist.Dockerfile
          images: ghcr.io/espressosystems/espresso-sequencer/cdn-whitelist
          platforms: ${{ env.DOCKER_PLATFORMS }}
          push: ${{ github.event_name != 'pull_request' }}

      - name: Build state-relay-server docker image
        uses: ./.github/actions/docker-image
        with:
          file: ./docker/state-relay-server.Dockerfile
          images: ghcr.io/espressosystems/espresso-sequencer/state-relay-server
          platforms: ${{ env.DOCKER_PLATFORMS }}
          push: ${{ github.event_name != 'pull_request' }}

      - name: Build prover-service docker image
        uses: ./.github/actions/docker-image
        with:
          file: ./docker/prover-service.Dockerfile
          images: ghcr.io/espressosystems/espresso-sequencer/prover-service
          platforms: ${{ env.DOCKER_PLATFORMS }}
          push: ${{ github.event_name != 'pull_request' }}

      - name: Build orchestrator docker image
        uses: ./.github/actions/docker-image
        with:
          file: ./docker/orchestrator.Dockerfile
          images: ghcr.io/espressosystems/espresso-sequencer/orchestrator
          platforms: ${{ env.DOCKER_PLATFORMS }}
          push: ${{ github.event_name != 'pull_request' }}

      - name: Build submit-transactions docker image
        uses: ./.github/actions/docker-image
        with:
          file: ./docker/submit-transactions.Dockerfile
          images: ghcr.io/espressosystems/espresso-sequencer/submit-transactions
          platforms: ${{ env.DOCKER_PLATFORMS }}
          push: ${{ github.event_name != 'pull_request' }}

      - name: Build deploy docker image
        uses: ./.github/actions/docker-image
        with:
          file: ./docker/deploy.Dockerfile
          images: ghcr.io/espressosystems/espresso-sequencer/deploy
          platforms: ${{ env.DOCKER_PLATFORMS }}
          push: ${{ github.event_name != 'pull_request' }}

      - name: Build builder docker image
        uses: ./.github/actions/docker-image
        with:
          file: ./docker/builder.Dockerfile
          images: ghcr.io/espressosystems/espresso-sequencer/builder
          platforms: ${{ env.DOCKER_PLATFORMS }}
          push: ${{ github.event_name != 'pull_request' }}

      - name: Build nasty-client docker image
        uses: ./.github/actions/docker-image
        with:
          file: ./docker/nasty-client.Dockerfile
          images: ghcr.io/espressosystems/espresso-sequencer/nasty-client
          platforms: ${{ env.DOCKER_PLATFORMS }}
          push: ${{ github.event_name != 'pull_request' }}

      - name: Build update-permissioned-stake-table docker image
        uses: ./.github/actions/docker-image
        with:
          file: ./docker/update-permissioned-stake-table.Dockerfile
          images: ghcr.io/espressosystems/espresso-sequencer/update-permissioned-stake-table
          platforms: ${{ env.DOCKER_PLATFORMS }}
          push: ${{ github.event_name != 'pull_request' }}

      - name: Build espresso-dev-node docker image
        uses: ./.github/actions/docker-image
        with:
          file: ./docker/espresso-dev-node.Dockerfile
          images: ghcr.io/espressosystems/espresso-sequencer/espresso-dev-node
          platforms: ${{ env.DOCKER_PLATFORMS }}
          push: ${{ github.event_name != 'pull_request' }}

      - name: Build bridge docker image
        uses: ./.github/actions/docker-image
        with:
          file: ./docker/bridge.Dockerfile
          images: ghcr.io/espressosystems/espresso-sequencer/bridge
          platforms: ${{ env.DOCKER_PLATFORMS }}
          push: ${{ github.event_name != 'pull_request' }}

      - name: Build marketplace-solver docker image
        uses: ./.github/actions/docker-image
        with:
          file: ./docker/marketplace-solver.Dockerfile
          images: ghcr.io/espressosystems/espresso-sequencer/marketplace-solver
          platforms: ${{ env.DOCKER_PLATFORMS }}
          push: ${{ github.event_name != 'pull_request' }}

      - name: Build marketplace-builder docker image
        uses: ./.github/actions/docker-image
        with:
          file: ./docker/marketplace-builder.Dockerfile
          images: ghcr.io/espressosystems/espresso-sequencer/marketplace-builder
          platforms: ${{ env.DOCKER_PLATFORMS }}
          push: ${{ github.event_name != 'pull_request' }}

      - name: Build node-validator docker image
        uses: ./.github/actions/docker-image
        with:
          file: ./docker/node-validator.Dockerfile
          images: ghcr.io/espressosystems/espresso-sequencer/node-validator
          platforms: ${{ env.DOCKER_PLATFORMS }}
          push: ${{ github.event_name != 'pull_request' }}

      - name: Build dev-rollup docker image
        uses: ./.github/actions/docker-image
        with:
          file: ./docker/dev-rollup.Dockerfile
          images: ghcr.io/espressosystems/espresso-sequencer/dev-rollup
          platforms: ${{ env.DOCKER_PLATFORMS }}
          push: ${{ github.event_name != 'pull_request' }}

      - name: Build staking-cli docker image
        uses: ./.github/actions/docker-image
        with:
          file: ./docker/staking-cli.Dockerfile
          images: ghcr.io/espressosystems/espresso-sequencer/staking-cli
          platforms: ${{ env.DOCKER_PLATFORMS }}
          push: ${{ github.event_name != 'pull_request' }}

  test-demo:
    if: ${{ github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    needs: [build-dockers]
    steps:
      - name: Install just command runner
        run: |
          sudo snap install --edge --classic just
          just --version

      - name: Checkout Repository
        uses: actions/checkout@v4

      # TODO: MA: not sure this works, but if not, why not?
      - name: Pull docker images
        run: |
          just pull

      - name: Test docker demo
        run: |
          just demo &
          set -o pipefail
          timeout -v 600 scripts/smoke-test-demo | sed -e 's/^/smoke-test: /;'
