name: Static Build
on:
  push:
    branches:
      - main
      - release-*
    tags:
      # YYYYMMDD
      - "20[0-9][0-9][0-1][0-9][0-3][0-9]*"
  schedule:
    - cron: "0 0 * * 1"
  pull_request:
  workflow_dispatch:

jobs:
  static-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - amd
          - arm
    steps:
      - name: Prepare ADM
        if: ${{ matrix.arch == 'linux/amd' }}
        run: |
          echo "TARGET=x86_64-unknown-linux-musl" >> $GITHUB_ENV
          echo "DEVSHELL=.#crossShell" >> $GITHUB_ENV
          echo "PLATFORM=linux/amd64" >> $GITHUB_ENV

      - name: Prepare ARM
        if: ${{ matrix.arch == 'arm' }}
        run: |
          echo "TARGET=aarch64-unknown-linux-musl" >> $GITHUB_ENV
          echo "DEVSHELL=.#armCrossShell" >> $GITHUB_ENV
          echo "PLATFORM=arm64" >> $GITHUB_ENV

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v22

      - uses: cachix/cachix-action@v12
        # If PR is from a non-collaborator (e. g. dependabot) the secrets are missing and the login to cachix fails.
        continue-on-error: true
        with:
          name: espresso-systems-private
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          extraPullNames: nix-community

      - name: Cache cargo
        uses: actions/cache@v3.3.1
        with:
          path: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git
            target
          key: espresso-sequencer-static-${{matrix.platform}}-v4-${{ hashFiles('Cargo.lock') }}

      - name: Fix Git Security Issue
        run: git config --global --add safe.directory "$PWD"

      - name: Compile all executables
        # timeout-minutes: 120
        run: |
          nix develop $DEVSHELL --accept-flake-config --option sandbox relaxed -c cargo build --release

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.TARGET }}-services
          path: |
            target/${{ env.TARGET }}/release/cdn-server
            target/${{ env.TARGET }}/release/sequencer
            target/${{ env.TARGET }}/release/example-l2
            target/${{ env.TARGET }}/release/cli

  static-dockers:
    runs-on: ubuntu-latest
    needs: static-build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download executables
        uses: actions/download-artifact@v3
        with:
          name: x86_64-unknown-linux-musl-services
          path: target/release

      - name: Setup Docker BuildKit (buildx)
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Container Repo
        uses: docker/login-action@v2
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate sequencer docker metadata
        uses: docker/metadata-action@v4
        id: sequencer
        with:
          images: ghcr.io/espressosystems/espresso-sequencer/sequencer

      - name: Generate cdn-server docker metadata
        uses: docker/metadata-action@v4
        id: cdn-server
        with:
          images: ghcr.io/espressosystems/espresso-sequencer/cdn-server

      - name: Generate example rollup metadata
        uses: docker/metadata-action@v4
        id: example-rollup
        with:
          images: ghcr.io/espressosystems/espresso-sequencer/example-rollup

      - name: Build and push sequencer docker
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./docker/sequencer.Dockerfile
          platforms: ${{ env.PLATFORM }}
          # push: ${{ github.event_name != 'pull_request' }}
          tags: |
            espressosystems/espresso-sequencer/sequencer:${{ matrix.arch }}-${{ github.sha }}
            espressosystems/espresso-sequencer/sequencer:${{ matrix.arch }}-latest
          labels: ${{ steps.sequencer.outputs.labels }}

      - name: Build and push cdn-server docker
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./docker/cdn-server.Dockerfile
          platforms: ${{ env.PLATFORM }}
          # push: ${{ github.event_name != 'pull_request' }}
          tags: |
            espressosystems/espresso-sequencer/cdn-server:${{ matrix.arch }}-${{ github.sha }}
            espressosystems/espresso-sequencer/cdn-server:${{ matrix.arch }}-latest
          labels: ${{ steps.cdn-server.outputs.labels }}

      - name: Build and push example-rollup docker
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./docker/example-rollup.Dockerfile
          platforms: ${{ env.PLATFORM }}
          # push: ${{ github.event_name != 'pull_request' }}
          tags: |
            espressosystems/espresso-sequencer/example-rollup:${{ matrix.arch }}-${{ github.sha }}
            espressosystems/espresso-sequencer/example-rollup:${{ matrix.arch }}-latest
          labels: ${{ steps.example-rollup.outputs.labels }}

  push-manifest:
    needs: static-dockers
    runs-on: ubuntu-latest
    steps:
      - name: Login to Github Container Repo
        uses: docker/login-action@v2
        # if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push manifest images, commit
        uses: Noelware/docker-manifest-action@master
        with:
          inputs: |
            ghcr.io/espressosystems/espresso-sequencer/sequencer:amd-${{ github.sha }},
            ghcr.io/espressosystems/espresso-sequencer/sequencer:arm-${{ github.sha }}
          images: ghcr.io/espressosystems/espresso-sequencer/sequencer:${{ github.sha }}
          push: true

      # - name: Create and push manifest images, latest
      #   uses: Noelware/docker-manifest-action@master
      #   with:
      #     inputs: |
      #       ghcr.io/espressosystems/espresso-sequencer/sequencer:amd-latest,
      #       ghcr.io/espressosystems/espresso-sequencer/sequencer:arm-latest
      #     images: ghcr.io/espressosystems/espresso-sequencer/sequencer:latest
      #     push: true
