name: Clippy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  clippy:
    name: Run Clippy  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Clippy
        run: cargo clippy --workspace --features testing --all-targets -- -D warnings