name: Coverage

on:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
      - release-*
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:

  CARGO_TERM_COLOR: always
  NEXTEST_PROFILE: coverage
  COVERAGE_RUSTFLAGS: >
    -Z threads=8 --cfg async_executor_impl="async-std" --cfg async_channel_impl="async-std" --cfg
    hotshot_example

jobs:
  code-coverage:
    runs-on: buildjet-16vcpu-ubuntu-2204
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview

      - name: Enable Rust Caching
        uses: Swatinem/rust-cache@v2


      - uses: taiki-e/install-action@cargo-llvm-cov
      - uses: taiki-e/install-action@nextest

      # Separate build step for easier identification of failures and timings.
      - name: Build tests for coverage
        run: |
          cargo +nightly llvm-cov --no-report nextest --all-features
          cargo +nightly llvm-cov --no-report --doc --all-features
        env:
          RUSTFLAGS: ${{ env.COVERAGE_RUSTFLAGS }}
        timeout-minutes: 90

      # TODO investigate why `uint_bytes` fail in coverage runs
      - name: Run tests with coverage
        run: |
          cargo +nightly llvm-cov report --doctests --lcov --output-path lcov.info
        env:
          RUSTFLAGS: ${{ env.COVERAGE_RUSTFLAGS }}
        timeout-minutes: 120

      - name: Coveralls upload
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          files: lcov.info
