name: HotShot integration tests

on:
  push:
    branches:
      - "main"
  pull_request:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ (github.ref == 'refs/heads/main' && github.run_number) || github.ref }}
  cancel-in-progress: true

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: taiki-e/install-action@just
      - uses: actions/checkout@v4
      - id: set-matrix
        run: echo "matrix=$(just hotshot::matrix)" >> "$GITHUB_OUTPUT"

  test:
    needs: build-matrix
    strategy:
      matrix: ${{ fromJson(needs.build-matrix.outputs.matrix) }}
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repository

      - name: Install Rust
        uses: mkroening/rust-toolchain-toml@main

      - uses: Swatinem/rust-cache@v2
        name: Enable Rust Caching
        with:
          shared-key: "hotshot-tests"
          cache-on-failure: "true"
          save-if: ${{ github.ref == 'refs/heads/main' && matrix.test_suites == 'test-ci-rest' }}
          prefix-key: v1-hotshot

      - uses: taiki-e/install-action@just

      - uses: taiki-e/install-action@nextest

      - name: Show memory
        run: free -h

      - name: Collect Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@v2
        with:
          comment_on_pr: false

      - name: Build integration tests
        run: |
          just hotshot::${{ matrix.test_suites }} --no-run
        timeout-minutes: 60

      - name: Run integration tests
        run: |
          just hotshot::${{ matrix.test_suites }} --no-fail-fast
        timeout-minutes: 60
        env:
          RUST_BACKTRACE: full

  test-examples:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repository

      - name: Install Rust
        uses: mkroening/rust-toolchain-toml@main

      - uses: Swatinem/rust-cache@v2
        name: Enable Rust Caching
        with:
          shared-key: "hotshot-examples"
          cache-on-failure: "true"
          save-if: ${{ github.ref == 'refs/heads/main' }}
          prefix-key: v0-hotshot

      - uses: taiki-e/install-action@just

      - name: Test examples
        run: |
          just hotshot::example all-push-cdn -- --config_file ./crates/hotshot/orchestrator/run-config.toml
        timeout-minutes: 20
