name: Lint

on:
  push:
    branches:
      - main
      - release-*
    tags:
      # YYYYMMDD
      - "20[0-9][0-9][0-1][0-9][0-3][0-9]*"
  pull_request:
    branches:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cargo-fmt:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rustfmt

      - name: Check formatting
        run: cargo +nightly fmt -- --check

  clippy-postgres:
    name: clippy (postgres)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/heads/main'  }}
          shared-key: cargo-clippy

      - name: Run clippy
        run: |
          cargo clippy --features testing --all-targets --keep-going -- -D warnings

  clippy-embedded:
      name: clippy (embedded-db)
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: Swatinem/rust-cache@v2
          with:
            save-if: false
            shared-key: cargo-clippy

        - name: Run clippy
          run: |
            cargo clippy --workspace --features "embedded-db testing" --all-targets --keep-going -- -D warnings

  check-individually:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@just
      - uses: dtolnay/rust-toolchain@stable
      - run: just check-individually

