name: Rust + Node.js Special Test

on:
  workflow_dispatch: 
  pull_request:
  push:
    tags:
      # YYYYMMDD
      - "20[0-9][0-9][0-1][0-9][0-3][0-9]*"
  schedule:
    - cron: "0 0 * * 1"
    paths:
      - 'contracts/rust/deployer/**'
      - '.github/workflows/rust-node-special-test.yml'
env:
  RUST_LOG: info,libp2p=off,node=error
  CARGO_TERM_COLOR: always
jobs:
  test-nodejs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Node.js dependencies
        run: |
          npm install

      - name: Run specific Rust test
        run: cargo test -p espresso-contract-deployer --features nodejs test_upgrade_light_client_to_v2_multisig_owner_dry_run -- --nocapture
