[package]
name = "hotshot-contract-adapter"
description = "Cross-domain (between Solidity and Rust) utilities for type conversion and testing"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

# Contract bindings docs fail to compile
[lib]
doctest = false

[[bin]]
name = "eval-domain"
path = "src/bin/eval_domain.rs"

[dependencies]
alloy = { workspace = true }
anyhow = { workspace = true }
ark-bn254 = { workspace = true }
ark-ec = { workspace = true }
ark-ed-on-bn254 = { workspace = true }
ark-ff = { workspace = true }
ark-poly = { workspace = true }
ark-serialize = { workspace = true }
ark-std = { workspace = true }
derive_more = { workspace = true }
hotshot-types = { workspace = true }
jf-pcs = { workspace = true }
jf-plonk = { workspace = true }
jf-signature = { workspace = true, features = ["bls", "schnorr"] }
jf-utils = { workspace = true }
num-bigint = { version = "0.4", default-features = false }
num-traits = { version = "0.2", default-features = false }
rand = { workspace = true }
serde = { workspace = true }
serde_arrays = "0.2.0"
thiserror = { workspace = true }
jf-plonk-compat = { package = "jf-plonk", git = "https://github.com/EspressoSystems/jellyfish", branch = "jf-relation-v0.5.0-compat", features = [
    "std",
] }

[dev-dependencies]
bincode = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }

[lints]
workspace = true
